### ISSUE TITLE
Query DeepSpeed MII with FastAPI and GRPC crashing

### ISSUE THREAD

**Issue by mallorbc** [microsoft/DeepSpeed-MII#130]
I am trying to use this with FastAPI. However, doing so leads to a variety of issues. 

I know the issue is a least in part related to event loop.  If I naively try to call the generator.query function I get an error about how there is already an event loop running.  Googling this issue leads me to this partial fix found here:
https://stackoverflow.com/questions/468270

By installing and using nest_asyncio I am able to partially solve the issue.  What I mean is that I am able to query the model, but only so much before the GRPC server shuts down.  I am not sure if the issues are related.

My environment is a docker container based on nvidia/cuda:11.6.1-devel-ubuntu20.04

```
Exception in callback PollerCompletionQueue._handle_events(<_UnixSelecto...e debug=False>)()
handle: <Handle PollerCompletionQueue._handle_events(<_UnixSelecto...e debug=False>)()>
Traceback (most recent call last):
  File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: cannot enter context: <Context object at 0x7fcdbc8950c0> is already entered
INFO:     172.31.0.1:44540 - "POST /generate/ HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.8/dist-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.8/dist-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/local/lib/python3.8/dist-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/usr/local/lib/python3.8/dist-packages/fastapi/routing.py", line 235, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.8/dist-packages/fastapi/routing.py", line 163, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/usr/local/lib/python3.8/dist-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/usr/local/lib/python3.8/dist-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.8/dist-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/lib/python3.8/asyncio/futures.py", line 260, in __await__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.8/asyncio/tasks.py", line 349, in __wakeup
    future.result()
  File "/usr/lib/python3.8/asyncio/futures.py", line 178, in result
    raise self._exception
  File "/usr/local/lib/python3.8/dist-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/app/./server_deepspeed.py", line 18, in generate
    return app_runner.generate(request,post_data)
  File "/app/./app_deepspeed.py", line 83, in generate
    status,context = self.async_generate(hash_key,post_data_dict)
  File "/app/./app_deepspeed.py", line 163, in async_generate
    gen_text = self.generator.query({"query": prompt}, do_sample=do_sample, max_length=total_max_length,min_length=total_min_length,top_k=top_k_input, top_p=top_p_input, temperature=temp_input,repetition_penalty=rep_penalty_input,early_stopping=early_stopping_input).response
  File "/usr/local/lib/python3.8/dist-packages/mii/server_client.py", line 369, in query
    response = self.asyncio_loop.run_until_complete(
  File "/usr/local/lib/python3.8/dist-packages/nest_asyncio.py", line 90, in run_until_complete
    return f.result()
  File "/usr/lib/python3.8/asyncio/futures.py", line 178, in result
    raise self._exception
  File "/usr/lib/python3.8/asyncio/tasks.py", line 282, in __step
    result = coro.throw(exc)
  File "/usr/local/lib/python3.8/dist-packages/mii/server_client.py", line 265, in _query_in_tensor_parallel
    await responses[0]
  File "/usr/lib/python3.8/asyncio/futures.py", line 260, in __await__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.8/asyncio/tasks.py", line 349, in __wakeup
    future.result()
  File "/usr/lib/python3.8/asyncio/futures.py", line 178, in result
    raise self._exception
  File "/usr/lib/python3.8/asyncio/tasks.py", line 280, in __step
    result = coro.send(None)
  File "/usr/local/lib/python3.8/dist-packages/mii/server_client.py", line 277, in _request_async_response
    response = await self.stubs[stub_id].GeneratorReply(req)
  File "/usr/local/lib/python3.8/dist-packages/grpc/aio/_call.py", line 290, in __await__
    raise _create_rpc_error(self._cython_call._initial_metadata,
grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Socket closed"
	debug_error_string = "UNKNOWN:Error received from peer ipv4:127.0.0.1:50050 {created_time:"2022-12-30T09:04:52.259477476+00:00", grpc_status:14, grpc_message:"Socket closed"}"
>
[2022-12-30 09:04:53,279] [INFO] [launch.py:318:sigkill_handler] Killing subprocess 105
[2022-12-30 09:04:53,279] [ERROR] [launch.py:324:sigkill_handler] ['/usr/bin/python3', '-m', 'mii.launch.multi_gpu_server', '--task-name', 'text-generation', '--model', 'gptj_dataset3_filtered_checkpoint900', '--model-path', '/tmp/mii_models', '--port', '50050', '--ds-optimize', '--provider', 'hugging-face', '--config', 'eyJ0ZW5zb3JfcGFyYWxsZWwiOiAxLCAicG9ydF9udW1iZXIiOiA1MDA1MCwgImR0eXBlIjogInRvcmNoLmZsb2F0MTYiLCAibG9hZF93aXRoX3N5c19tZW0iOiBmYWxzZSwgImVuYWJsZV9jdWRhX2dyYXBoIjogZmFsc2UsICJjaGVja3BvaW50X2RpY3QiOiBudWxsLCAiZGVwbG95X3JhbmsiOiBbMF0sICJ0b3JjaF9kaXN0X3BvcnQiOiAyOTUwMCwgImhmX2F1dGhfdG9rZW4iOiBudWxsLCAicmVwbGFjZV93aXRoX2tlcm5lbF9pbmplY3QiOiB0cnVlLCAicHJvZmlsZV9tb2RlbF90aW1lIjogZmFsc2UsICJza2lwX21vZGVsX2NoZWNrIjogdHJ1ZSwgIm1heF90b2tlbnMiOiAyMDQ4fQ=='] exits with return code = -8
```

**Comment by mrwyattii** [comment]
@mallorbc thanks for reporting this issue. In order to better understand the problem and provide a solution, it would be very helpful to have a small reproducing example. Are you able to provide one?

Thanks!

**Comment by mallorbc** [comment]
@mrwyattii Thanks for the response.  I now believe that the issue is related to DeepSpeed itself rather than DeepSpeed MII.  In my attempts to fix the issue, I tried running just DeepSpeed without DeepSpeed MII, as looking at the code makes me think that as long as you are ok with just one GPU, that shouldn't be a problem.

Doing so lead to some success, but to another issue with similar behavior to the one I report here.  After a seemingly random number of runs, I get an error 
```Floating point exception (core dumped)```

Due to the similar behavior and the fact that this repo relies on DeepSpeed, I suspect that this is the source of the issue, causing the server to crash.

I will provide a short script to repeat the error soon.  I will do so with both DeepSpeed and DeepSpeed MII.

**Comment by mallorbc** [comment]
See the programs at the link here https://github.com/mallorbc/Finetune_GPTNEO_GPTJ6B/tree/main/inference/benchmark
They contain scripts to rapidly test GPTJ with pytorch, DeepSpeed, and DeepSpeedMII(once deployed).

Both DeepSpeed and DeepSpeed MII fail around the same time.

**Comment by mrwyattii** [comment]
Thanks for providing some code to reproduce. I'm also seeing the behavior you described. Interestingly, when using other inputs I don't see this issue. Could you please share the full stack trace you are seeing so I can confirm we are seeing the exact same error? In particular, I am seeing the error pop up in a softmax function in `transformer_inference.so`.

**Comment by mallorbc** [comment]
I think I may have further narrowed down the issue.  When I was originally testing the model I was using just "<|endoftext|>" or "" for the input.  Unless I just experience a fluke, or unless one of the many different PRs of DeepSpeed partially fixed the issue, I may have narrowed it down to it occurring only for tiny or empty inputs.

I will test this more and share the results.  If I get an error again for inputs containing tokens. I will share the trace.  If I do not get an error, I will try again with no input and share the trace.

**Comment by mallorbc** [comment]
If what I just shared is correct, I feel like what I am saying is related to this issue and I just found out that if you give many short inputs it breaks.

https://github.com/microsoft/DeepSpeed/issues/2644

**Comment by mallorbc** [comment]
After doing a good bit of testing, I think the issue is more limited to just small or empty inputs(which should still be valid, but I can live with for my use cases).

I will still share stack trace soon and leave the issue open since it's an issue, but a more defined, more manageable one.
