### ISSUE TITLE
How to do the batch inference

### ISSUE THREAD

**Issue by Emerald01** [microsoft/DeepSpeed-MII#133]
Hello,
I am new explorer of MII. 
When I am trying to do the batch inference, something like this
```
start_text = ["blablabla..."]
batch_size = 10
result = generator.query({"query": start_text * batch_size})
```
It looks like it is doing a sequential inference, where the time is accumulating with the size of batch

So I did this
```
start_text = ["blablabla..."]
batch_size = 10
result = generator.query({"query": start_text * batch_size}, batch_size=batch_size)
```
I got the error
```
Pipeline with tokenizer without pad_token cannot do batching. You can try to set it with `pipe.tokenizer.pad_token_id = model.config.eos_token_id`."
```
I think I am close, since I know this error seems coming from the Huggingface pipeline with deepspeed.init_inference(), I can setup in this way, but I do not know how MII can set this up because everything is wrapped up

Thank you!

**Comment by mrwyattii** [comment]
Hi @Emerald01 and thanks for reporting this issue. Can you provide a bit more detail, like which model and task you are using?

**Comment by Emerald01** [comment]
Hello @mrwyattii , thank you for helping.

We are trying to see how DeepSpeed MII can ease our work to host models in a lower cost and high efficiency. We are testing CodeGen (although it is not directly supported by MII, but by skipping model check, it can run very well, as discussed by another issue), but we are also going to test other much larger models.

If we do not do the batch infer, it runs very well. But when I have a batch input like a list of prompts in this example, the output latency is linear with the size of the batch, therefore I wonder if there is a way to do the batch inference, and then I used `batch_size=`, it looks correct but I got the above error. In the original DeepSpeed + pipeline, I can correct this very easily like setting `pipe.tokenizer.pad_token_id = pipe.model.config.eos_token_id`, but since MII wraps things up, I am not sure how I should interact with your APIs to make the tokenizer happy with batching.

If you have any suggestions, or if I missed anything, please let me know. Thank you so much!
```
import mii
import time

batch_size = 10
new_tokens = 128

mii_configs = {"tensor_parallel": 1, "dtype": "fp16", "skip_model_check": True}

mii.deploy(task="text-generation",
           model="Salesforce/codegen-16B-multi",
           deployment_name="codegen16Bmulti_deployment",
           mii_config=mii_configs,
           enable_deepspeed=True,
           enable_zero=False,
           )

generator = mii.mii_query_handle("codegen16Bmulti_deployment")

start_text = ["Calculate the mean of ask, bid and volume respectively for Bitcoin's over the past 10 days"]

# benchmark
t0 = time.time()
result = generator.query({"query": start_text * batch_size},
                         # batch_size=batch_size,
                         do_sample=False,
                         max_new_tokens=new_tokens,
                         pad_token_id=50256)
torch.cuda.synchronize()
t1 = time.time()
```

**Comment by mrwyattii** [comment]
@Emerald01 I was able to reproduce the problem on my system. We currently don't have a method in the MII API to make the changes necessary to fix this tokenizer padding issue. However, I think this would be value to add in the future. I will have to discuss with the team how we want to enable this sort of functionality.

In the meantime, you can fix the problem by installing a patched version:
1. `git clone https://github.com/microsoft/DeepSpeed-MII.git`
2. `cd DeepSpeed-MII`
3. `touch tokenizer_padding.patch`
4. Use your favorite text editor to open `tokenizer_padding.patch` and paste in the following:
```
diff --git a/mii/models/load_models.py b/mii/models/load_models.py
index 431fc34..5beb1a1 100644
--- a/mii/models/load_models.py
+++ b/mii/models/load_models.py
@@ -43,6 +43,7 @@ def load_models(task_name,
             assert mii_config.dtype == torch.half or mii_config.dtype == torch.int8, "Bloom models only support fp16/int8"
             assert mii_config.enable_cuda_graph == False, "Bloom models do no support Cuda Graphs"
         inference_pipeline = hf_provider(model_path, model_name, task_name, mii_config)
+        inference_pipeline.tokenizer.pad_token_id = inference_pipeline.model.config.eos_token_id
     elif provider == mii.constants.ModelProvider.ELEUTHER_AI:
         from mii.models.providers.eleutherai import eleutherai_provider
         assert mii_config.dtype == torch.half, "gpt-neox only support fp16"
```
5. `git apply tokenizer_padding.patch`
6. `pip install .`

Please let me know if this works and look forward to future development that will allow more customization of the pipeline objects!

**Comment by Emerald01** [comment]
@mrwyattii 
It works! Thank you.
However, I notice that each GPU actually got the size of original model instead of splitting the model to individual as I thought. I guess this is a separate issue, but I just wanna bring it up to see if we have any quick solution.

Here is part of the log, it confirms I turned on 2 GPUs
```
[2023-01-26 17:51:19,823] [INFO] [launch.py:135:main] 0 NCCL_VERSION=2.11.4
[2023-01-26 17:51:19,823] [INFO] [launch.py:142:main] WORLD INFO DICT: {'localhost': [0, 1]}
[2023-01-26 17:51:19,823] [INFO] [launch.py:148:main] nnodes=1, num_local_procs=2, node_rank=0
[2023-01-26 17:51:19,823] [INFO] [launch.py:161:main] global_rank_mapping=defaultdict(<class 'list'>, {'localhost': [0, 1]})
[2023-01-26 17:51:19,823] [INFO] [launch.py:162:main] dist_world_size=2
[2023-01-26 17:51:19,823] [INFO] [launch.py:164:main] Setting CUDA_VISIBLE_DEVICES=0,1
...
[2023-01-26 18:00:03,542] [INFO] [server_client.py:117:_wait_until_server_is_live] waiting for server to start...
> --------- MII Settings: ds_optimize=True, replace_with_kernel_inject=True, enable_cuda_graph=False 
[2023-01-26 18:00:06,951] [INFO] [logging.py:68:log_dist] [Rank -1] DeepSpeed info: version=0.8.0, git-hash=unknown, git-branch=unknown
[2023-01-26 18:00:06,952] [INFO] [logging.py:68:log_dist] [Rank -1] quantize_bits = 8 mlp_extra_grouping = False, quantize_groups = 1
[2023-01-26 18:00:06,955] [INFO] [comm.py:657:init_distributed] Initializing TorchBackend in DeepSpeed with backend nccl
[2023-01-26 18:00:08,547] [INFO] [server_client.py:117:_wait_until_server_is_live] waiting for server to start...
> --------- MII Settings: ds_optimize=True, replace_with_kernel_inject=True, enable_cuda_graph=False 
[2023-01-26 18:00:09,732] [INFO] [logging.py:68:log_dist] [Rank -1] DeepSpeed info: version=0.8.0, git-hash=unknown, git-branch=unknown
[2023-01-26 18:00:09,733] [INFO] [logging.py:68:log_dist] [Rank -1] quantize_bits = 8 mlp_extra_grouping = False, quantize_groups = 1
About to start server
...

Finally, when I run batch_size = 32, it raises the OOM. I see it has used about 36G, which is the size of the entire model. I thought each device may only get half of the model around 18G. Is my understanding wrong somewhere?
```
debug_error_string = "UNKNOWN:Error received from peer ipv4:127.0.0.1:50050 {grpc_message:"Exception calling application: CUDA out of memory. Tried to allocate 66.00 MiB (GPU 0; 39.59 GiB total capacity; 36.40 GiB already allocated; 68.19 MiB free; 36.78 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF", grpc_status:2, created_time:"2023-01-26T18:00:55.029350976+00:00"}"
```

```

**Comment by mrwyattii** [comment]
@Emerald01 The reason you are not seeing memory savings is because DeepSpeed-inference does not support automatic kernel injection with Codegen models at this time. Without the DeepSpeed kernels, we do not shard the model across GPUs. If you were to test with a model where we do support automatic injection (e.g., `gpt2`), you would see the memory per GPU is reduced.

We do allow custom injection policies for models where we do not support automatic kernel injection. You can see an example of that in our unit tests: https://github.com/microsoft/DeepSpeed/blob/ef6a958e70fe0106afbff9c2c885878cc659f4ac/tests/unit/inference/test_inference.py#L405

Additionally, you can also use ZeRO to offload from GPU memory. See our example here: https://github.com/microsoft/DeepSpeed-MII/blob/main/examples/local/text-generation-zero-example.py

**Comment by satpalsr** [comment]
@mrwyattii I added this line
`inference_pipeline.tokenizer.pad_token_id = inference_pipeline.model.config.eos_token_id`
after this
https://github.com/microsoft/DeepSpeed-MII/blob/737c2477ce377c1678940e6dff62d838ad43d205/mii/models/load_models.py#L47

However, I get
```
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Traceback (most recent call last):
  File "gen.py", line 9, in <module>
    result = generator.query({"query": ["DeepSpeed is", "Seattle is"]*batch_size}, do_sample=True, max_new_tokens=100 , batch_size=batch_size) # 
  File "/admin/home/DeepSpeed-MII/mii/client.py", line 125, in query
    response = self.asyncio_loop.run_until_complete(
  File "/admin/home/anaconda3/envs/test/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/admin/home/DeepSpeed-MII/mii/client.py", line 109, in _query_in_tensor_parallel
    await responses[0]
  File "/admin/home/DeepSpeed-MII/mii/client.py", line 72, in _request_async_response
    proto_response = await getattr(self.stub, conversions["method"])(proto_request)
  File "/admin/home/anaconda3/envs/test/lib/python3.8/site-packages/grpc/aio/_call.py", line 290, in __await__
    raise _create_rpc_error(self._cython_call._initial_metadata,
grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
        status = StatusCode.UNKNOWN
        details = "Exception calling application: The specified pointer resides on host memory and is not registered with any CUDA device."
        debug_error_string = "UNKNOWN:Error received from peer ipv6:%5B::1%5D:50050 {created_time:"2023-04-15T05:32:19.698693653+00:00", grpc_status:2, grpc_message:"Exception calling application: The specified pointer resides on host memory and is not registered with any CUDA device."}"
```

**Comment by satpalsr** [comment]
Hey @mrwyattii can you look into this or assign someone.
