### ISSUE TITLE
 checkpoint   str type expected (type=type_error.str)

### ISSUE THREAD

**Issue by vamsikrishnav** [microsoft/DeepSpeed-MII#150]
While running the deepspeed-mii inference server for bloom int8 model I get the below error:

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
[2023-02-17 08:28:53,124] [INFO] [logging.py:68:log_dist] [Rank 0] DeepSpeed info: version=0.8.0, git-hash=unknown, git-branch=unknown
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    exec(code, run_globals)
  File "/mnt/disk1/ds-mii/mii/lib/python3.8/site-packages/mii/launch/multi_gpu_server.py", line 70, in <module>
Traceback (most recent call last):
    main()
  File "/mnt/disk1/ds-mii/mii/lib/python3.8/site-packages/mii/launch/multi_gpu_server.py", line 56, in main
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
Traceback (most recent call last):
    inference_pipeline = load_models(task_name=args.task_name,
  File "/mnt/disk1/ds-mii/mii/lib/python3.8/site-packages/mii/models/load_models.py", line 83, in load_models
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
Traceback (most recent call last):
    engine = deepspeed.init_inference(getattr(inference_pipeline,
  File "/mnt/disk1/ds-mii/mii/lib/python3.8/site-packages/deepspeed/__init__.py", line 309, in init_inference
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    ds_inference_config = DeepSpeedInferenceConfig(**config_dict)
    return _run_code(code, main_globals, None,
    return _run_code(code, main_globals, None,
  File "/mnt/disk1/ds-mii/mii/lib/python3.8/site-packages/deepspeed/runtime/config_utils.py", line 55, in __init__
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    super().__init__(**data)
  File "pydantic/main.py", line 342, in pydantic.main.BaseModel.__init__
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/mnt/disk1/ds-mii/mii/lib/python3.8/site-packages/mii/launch/multi_gpu_server.py", line 70, in <module>
    exec(code, run_globals)
  File "/mnt/disk1/ds-mii/mii/lib/python3.8/site-packages/mii/launch/multi_gpu_server.py", line 70, in <module>
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
    main()
  File "/mnt/disk1/ds-mii/mii/lib/python3.8/site-packages/mii/launch/multi_gpu_server.py", line 70, in <module>
  File "/mnt/disk1/ds-mii/mii/lib/python3.8/site-packages/mii/launch/multi_gpu_server.py", line 56, in main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
    main()
  File "/mnt/disk1/ds-mii/mii/lib/python3.8/site-packages/mii/launch/multi_gpu_server.py", line 70, in <module>
  File "/mnt/disk1/ds-mii/mii/lib/python3.8/site-packages/mii/launch/multi_gpu_server.py", line 56, in main
    inference_pipeline = load_models(task_name=args.task_name,
    main()
  File "/mnt/disk1/ds-mii/mii/lib/python3.8/site-packages/mii/launch/multi_gpu_server.py", line 56, in main
    return _run_code(code, main_globals, None,
  File "/mnt/disk1/ds-mii/mii/lib/python3.8/site-packages/mii/models/load_models.py", line 83, in load_models
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
pydantic.error_wrappers.ValidationError: 1 validation error for DeepSpeedInferenceConfig
checkpoint
  str type expected (type=type_error.str)
    exec(code, run_globals)
    main()
    inference_pipeline = load_models(task_name=args.task_name,
  File "/mnt/disk1/ds-mii/mii/lib/python3.8/site-packages/mii/launch/multi_gpu_server.py", line 70, in <module>
  File "/mnt/disk1/ds-mii/mii/lib/python3.8/site-packages/mii/launch/multi_gpu_server.py", line 56, in main
    inference_pipeline = load_models(task_name=args.task_name,
  File "/mnt/disk1/ds-mii/mii/lib/python3.8/site-packages/mii/models/load_models.py", line 83, in load_models
  File "/mnt/disk1/ds-mii/mii/lib/python3.8/site-packages/mii/models/load_models.py", line 83, in load_models
    engine = deepspeed.init_inference(getattr(inference_pipeline,
  File "/mnt/disk1/ds-mii/mii/lib/python3.8/site-packages/deepspeed/__init__.py", line 309, in init_inference
    exec(code, run_globals)
    inference_pipeline = load_models(task_name=args.task_name,
  File "/mnt/disk1/ds-mii/mii/lib/python3.8/site-packages/mii/launch/multi_gpu_server.py", line 70, in <module>
    main()
  File "/mnt/disk1/ds-mii/mii/lib/python3.8/site-packages/mii/models/load_models.py", line 83, in load_models
  File "/mnt/disk1/ds-mii/mii/lib/python3.8/site-packages/mii/launch/multi_gpu_server.py", line 56, in main
    engine = deepspeed.init_inference(getattr(inference_pipeline,
  File "/mnt/disk1/ds-mii/mii/lib/python3.8/site-packages/deepspeed/__init__.py", line 309, in init_inference
    engine = deepspeed.init_inference(getattr(inference_pipeline,
  File "/mnt/disk1/ds-mii/mii/lib/python3.8/site-packages/deepspeed/__init__.py", line 309, in init_inference
    inference_pipeline = load_models(task_name=args.task_name,
    engine = deepspeed.init_inference(getattr(inference_pipeline,
    main()
    ds_inference_config = DeepSpeedInferenceConfig(**config_dict)
  File "/mnt/disk1/ds-mii/mii/lib/python3.8/site-packages/deepspeed/__init__.py", line 309, in init_inference
  File "/mnt/disk1/ds-mii/mii/lib/python3.8/site-packages/mii/models/load_models.py", line 83, in load_models
  File "/mnt/disk1/ds-mii/mii/lib/python3.8/site-packages/mii/launch/multi_gpu_server.py", line 56, in main
  File "/mnt/disk1/ds-mii/mii/lib/python3.8/site-packages/deepspeed/runtime/config_utils.py", line 55, in __init__
    ds_inference_config = DeepSpeedInferenceConfig(**config_dict)
  File "/mnt/disk1/ds-mii/mii/lib/python3.8/site-packages/deepspeed/runtime/config_utils.py", line 55, in __init__
    ds_inference_config = DeepSpeedInferenceConfig(**config_dict)
    inference_pipeline = load_models(task_name=args.task_name,
    engine = deepspeed.init_inference(getattr(inference_pipeline,
  File "/mnt/disk1/ds-mii/mii/lib/python3.8/site-packages/deepspeed/runtime/config_utils.py", line 55, in __init__
    super().__init__(**data)
  File "/mnt/disk1/ds-mii/mii/lib/python3.8/site-packages/mii/models/load_models.py", line 83, in load_models
  File "/mnt/disk1/ds-mii/mii/lib/python3.8/site-packages/deepspeed/__init__.py", line 309, in init_inference
    ds_inference_config = DeepSpeedInferenceConfig(**config_dict)
  File "pydantic/main.py", line 342, in pydantic.main.BaseModel.__init__
    super().__init__(**data)
  File "/mnt/disk1/ds-mii/mii/lib/python3.8/site-packages/deepspeed/runtime/config_utils.py", line 55, in __init__
  File "pydantic/main.py", line 342, in pydantic.main.BaseModel.__init__
    super().__init__(**data)
  File "pydantic/main.py", line 342, in pydantic.main.BaseModel.__init__
    engine = deepspeed.init_inference(getattr(inference_pipeline,
  File "/mnt/disk1/ds-mii/mii/lib/python3.8/site-packages/deepspeed/__init__.py", line 309, in init_inference
    super().__init__(**data)
  File "pydantic/main.py", line 342, in pydantic.main.BaseModel.__init__
    ds_inference_config = DeepSpeedInferenceConfig(**config_dict)
  File "/mnt/disk1/ds-mii/mii/lib/python3.8/site-packages/deepspeed/runtime/config_utils.py", line 55, in __init__
    super().__init__(**data)
  File "pydantic/main.py", line 342, in pydantic.main.BaseModel.__init__
    ds_inference_config = DeepSpeedInferenceConfig(**config_dict)
  File "/mnt/disk1/ds-mii/mii/lib/python3.8/site-packages/deepspeed/runtime/config_utils.py", line 55, in __init__
    super().__init__(**data)
  File "pydantic/main.py", line 342, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for DeepSpeedInferenceConfig
checkpoint
  str type expected (type=type_error.str)
pydantic.error_wrappers.ValidationError: 1 validation error for DeepSpeedInferenceConfig
checkpoint
  str type expected (type=type_error.str)
pydantic.error_wrappers.ValidationError: 1 validation error for DeepSpeedInferenceConfig
checkpoint
  str type expected (type=type_error.str)
pydantic.error_wrappers.ValidationError: 1 validation error for DeepSpeedInferenceConfig
checkpoint
  str type expected (type=type_error.str)
pydantic.error_wrappers.ValidationError: 1 validation error for DeepSpeedInferenceConfig
checkpoint
  str type expected (type=type_error.str)
pydantic.error_wrappers.ValidationError: 1 validation error for DeepSpeedInferenceConfig
checkpoint
  str type expected (type=type_error.str)
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/mnt/disk1/ds-mii/mii/lib/python3.8/site-packages/mii/launch/multi_gpu_server.py", line 70, in <module>
    main()
  File "/mnt/disk1/ds-mii/mii/lib/python3.8/site-packages/mii/launch/multi_gpu_server.py", line 56, in main
    inference_pipeline = load_models(task_name=args.task_name,
  File "/mnt/disk1/ds-mii/mii/lib/python3.8/site-packages/mii/models/load_models.py", line 83, in load_models
    engine = deepspeed.init_inference(getattr(inference_pipeline,
  File "/mnt/disk1/ds-mii/mii/lib/python3.8/site-packages/deepspeed/__init__.py", line 309, in init_inference
    ds_inference_config = DeepSpeedInferenceConfig(**config_dict)
  File "/mnt/disk1/ds-mii/mii/lib/python3.8/site-packages/deepspeed/runtime/config_utils.py", line 55, in __init__
    super().__init__(**data)
  File "pydantic/main.py", line 342, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for DeepSpeedInferenceConfig
checkpoint
  str type expected (type=type_error.str)
```

My code is:

```
import mii
import time

mii_configs = {
    "dtype": "int8",
    "tensor_parallel": 8,
    "port_number": 50950,
    "skip_model_check": True,
}
name = "microsoft/bloom-deepspeed-inference-int8"

mii.deploy(task='text-generation',
           model=name,
           deployment_name="bloom176b_deployment",
           model_path="/mnt/disk1/",
           mii_config=mii_configs)

```

**Comment by alvin-c-shih** [comment]
Try monkey `patching mii/models/load_models.py` .
````
diff --git a/mii/models/load_models.py b/mii/models/load_models.py
index 431fc34..cc85c96 100644
--- a/mii/models/load_models.py
+++ b/mii/models/load_models.py
@@ -60,7 +60,13 @@ def load_models(task_name,
         assert mii_config.dtype == torch.half or mii_config.dtype == torch.int8, "Bloom models only support fp16/int8"
         assert mii_config.enable_cuda_graph == False, "Bloom models do no support Cuda Graphs"
         inference_pipeline = load_hf_llm(model_path, model_name, task_name, mii_config)
-        inf_config["checkpoint"] = inference_pipeline.checkpoint_dict
+
+        # Need to populate base_dir and checkpoint as per:
+        # https://github.com/microsoft/DeepSpeed/blob/master/deepspeed/inference/config.py#L204
+        base_dir = inference_pipeline.checkpoint_dict['base_dir']
+        inf_config["base_dir"] = base_dir
+        inf_config["checkpoint"] = os.path.join(base_dir, "ds_inference_config.json")
+
         if mii_config.dtype == torch.int8:
             if "enable_qkv_quantization" in inspect.signature(
                     deepspeed.init_inference).parameters:
````

**Comment by mrwyattii** [comment]
This issue should have been resolved in https://github.com/microsoft/DeepSpeed/pull/3007. If you are still experiencing this error, please reopen. Thanks
