### ISSUE TITLE
Unable to query running model on deepspeed-mii.

### ISSUE THREAD

**Issue by msinha251** [microsoft/DeepSpeed-MII#169]
Hi Team, 

I am trying to run `databricks/dolly-v1-6b` model with deepspeed-mii on AWS EC2 `g5.48x` machine. And I am able to successfully run this with below snippet by running `python dolly-v1-6b-mii.py`:

```
# dolly-v1-6b-mii.py

import mii
mii_configs = {"tensor_parallel": 8, "dtype": "torch.float16"}
mii.deploy(task="text-generation",
           model="databricks/dolly-v1-6b",
           deployment_name="dolly-v1-6b",
           mii_config=mii_configs)
```

output:
```
...
...
[2023-04-20 08:24:34,131] [INFO] [server_client.py:118:_wait_until_server_is_live] server has started on 50050
```

But I am unable to query it with below script by running `python query.py -d dolly-v1-6b`. Can someone please advice what is missing here ?

```
#query.py

# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: Apache-2.0

# DeepSpeed Team
import mii
import argparse

parser = argparse.ArgumentParser()
parser.add_argument('--deployment',
                    '-d',
                    type=str,
                    required=True,
                    help="deployment_name set in the MII deployment")
args = parser.parse_args()

generator = mii.mii_query_handle(args.deployment)
result = generator.query({'query': ["DeepSpeed is the", "Seattle is"]})
print(result.response)
print("time_taken:", result.time_taken)
```

Error:
```
Traceback (most recent call last):
  File "/home/ubuntu/.local/share/virtualenvs/api-4_HwkVju/lib/python3.10/site-packages/mii/server_client.py", line 275, in _request_async_response
    response = await self.stubs[stub_id].GeneratorReply(req)
  File "/home/ubuntu/.local/share/virtualenvs/api-4_HwkVju/lib/python3.10/site-packages/grpc/aio/_call.py", line 290, in __await__
    raise _create_rpc_error(self._cython_call._initial_metadata,
grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
        status = StatusCode.UNKNOWN
        details = "Exception calling application: 'Parameter' object has no attribute 'scale'"
        debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2023-04-20T08:30:06.422291205+00:00", grpc_status:2, grpc_message:"Exception calling application: \'Parameter\' object has no attribute \'scale\'"}"
```

Thanks

**Comment by msinha251** [comment]
It's working :) Issue was with my gpu config.
