### ISSUE TITLE
Add "deploy.py" file for deployment in AzureML into documentation 

### ISSUE THREAD

**Issue by natasha-savic-msft** [microsoft/DeepSpeed-MII#184]
Hello, I followed you steps for DeepSpeed deployment. Could you kindly add another step between setting up the az ml CLI and deploying the mii resource. To achieve this, run `python -m setup`. Then proceed with the steps from `cd ./bloom560m-deployment_aml`. It is not clear currently that `setup.py` performs the deployment containing the code snippet under "Deployment"

<img width="961" alt="image" src="https://github.com/microsoft/DeepSpeed-MII/assets/89967465/5fac488a-daa3-4380-8bd5-ea3ac50ef728">

**Comment by natasha-savic-msft** [comment]
Since no requirements.txt is provided for AzureML deployment, please also add dependencies. E.g. the transformers library needs an upgrade (`huggingface-hub-0.14.1 transformers-4.29.2`) otherwise `deploy.sh` fails with:

`Traceback (most recent call last):
  File "model_download.py", line 19, in <module>
    _ = AutoConfig.from_pretrained(model)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/transformers/models/auto/configuration_auto.py", line 632, in from_pretrained
    config_class = CONFIG_MAPPING[config_dict["model_type"]]
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/transformers/models/auto/configuration_auto.py", line 347, in __getitem__
    raise KeyError(key)
KeyError: 'bloom'`
