### ISSUE TITLE
Query DeepSpeed MII with GRPC ERROR WHEN USE MULTI GPU CARDS

### ISSUE THREAD

**Issue by zhaotyer** [microsoft/DeepSpeed-MII#185]
I deploy bigscience/bloom-560m using deepspeed-mii, when i use one gpu card by setting tensor_parallel=1,it's work well,
but when i setting tensor_parallel=2, the grpc server is able to start, but when i query ,the server will stop 

enviroment:
DeepSpeed general environment info:
torch install path ............... ['/usr/local/lib/python3.8/dist-packages/torch']
torch version .................... 1.13.0+cu117
deepspeed install path ........... ['/usr/local/lib/python3.8/dist-packages/deepspeed']
deepspeed info ................... 0.9.3+f1fab902, f1fab902, master
torch cuda version ............... 11.7
torch hip version ................ None
nvcc version ..................... 11.7
deepspeed wheel compiled w. ...... torch 1.13, cuda 11.7

GPU Info
![微信图片_20221128010627](https://github.com/microsoft/DeepSpeed-MII/assets/89376832/eff17e36-7f26-4e12-b0e7-56d2adfa7679)

deploy code is:

```
import mii

mii_configs = {"tensor_parallel": 2,"deploy_rank": [0,1] , "dtype": "fp16"}
mii.deploy(task='text-generation',
           model="bigscience/bloom-560m",
           model_path="/tmp/models/bloom-560m",
           deployment_name="bloom560m_deployment",
           mii_config=mii_configs)
```

query code is:

```
import mii
generator = mii.mii_query_handle("bloom560m_deployment")
result = generator.query({"query": ["DeepSpeed is", "1+1 is"]}, do_sample=True, max_new_tokens=30)
print(result)
```

Error info

[2023-05-16 20:47:28,349] [INFO] [server_client.py:118:_wait_until_server_is_live] server has started on 50050
root@172:/tmp/models# python3 text-generation-bloom560m-query.py 
------------------------------------------------------
Free memory : 22.155396 (GigaBytes)  
Total memory: 39.586060 (GigaBytes)  
Requested memory: 0.035156 (GigaBytes) 
Setting maximum total tokens (input + output) to 1024 
WorkSpace: 0x7f0060000000 
------------------------------------------------------
[2023-05-16 20:48:00,076] [INFO] [launch.py:428:sigkill_handler] Killing subprocess 2673
Traceback (most recent call last):
  File "text-generation-bloom560m-query.py", line 3, in <module>
    result = generator.query({"query": ["DeepSpeed is", "1+1 is"]}, do_sample=True, max_new_tokens=30)
  File "/usr/local/lib/python3.8/dist-packages/mii/server_client.py", line 367, in query
    response = self.asyncio_loop.run_until_complete(
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.8/dist-packages/mii/server_client.py", line 263, in _query_in_tensor_parallel
    await responses[0]
  File "/usr/local/lib/python3.8/dist-packages/mii/server_client.py", line 275, in _request_async_response
    response = await self.stubs[stub_id].GeneratorReply(req)
  File "/usr/local/lib/python3.8/dist-packages/grpc/aio/_call.py", line 290, in __await__
    raise _create_rpc_error(self._cython_call._initial_metadata,
grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Socket closed"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"Socket closed", grpc_status:14, created_time:"2023-05-16T20:48:29.028070584-07:00"}"
>
[2023-05-16 20:48:29,061] [INFO] [launch.py:428:sigkill_handler] Killing subprocess 2674
[2023-05-16 20:48:29,061] [ERROR] [launch.py:434:sigkill_handler] ['/usr/bin/python3', '-m', 'mii.launch.multi_gpu_server', '--task-name', 'text-generation', '--model', 'bigscience/bloom-560m', '--model-path', '/tmp/models/bloom-560m', '--port', '50050', '--ds-optimize', '--provider', 'hugging-face', '--config', 'eyJ0ZW5zb3JfcGFyYWxsZWwiOiAyLCAicG9ydF9udW1iZXIiOiA1MDA1MCwgImR0eXBlIjogInRvcmNoLmZsb2F0MTYiLCAibG9hZF93aXRoX3N5c19tZW0iOiBmYWxzZSwgImVuYWJsZV9jdWRhX2dyYXBoIjogZmFsc2UsICJjaGVja3BvaW50X2RpY3QiOiBudWxsLCAiZGVwbG95X3JhbmsiOiBbMCwgMV0sICJ0b3JjaF9kaXN0X3BvcnQiOiAyOTUwMCwgImhmX2F1dGhfdG9rZW4iOiBudWxsLCAicmVwbGFjZV93aXRoX2tlcm5lbF9pbmplY3QiOiB0cnVlLCAicHJvZmlsZV9tb2RlbF90aW1lIjogZmFsc2UsICJza2lwX21vZGVsX2NoZWNrIjogZmFsc2V9'] exits with return code = -7
Task exception was never retrieved
future: <Task finished name='Task-3' coro=<MIIServerClient._request_async_response() done, defined at /usr/local/lib/python3.8/dist-packages/mii/server_client.py:267> exception=<AioRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Socket closed"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"Socket closed", grpc_status:14, created_time:"2023-05-16T20:47:59.835752328-07:00"}"
>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/mii/server_client.py", line 275, in _request_async_response
    response = await self.stubs[stub_id].GeneratorReply(req)
  File "/usr/local/lib/python3.8/dist-packages/grpc/aio/_call.py", line 290, in __await__
    raise _create_rpc_error(self._cython_call._initial_metadata,
grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Socket closed"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"Socket closed", grpc_status:14, created_time:"2023-05-16T20:47:59.835752328-07:00"}"
>

expect:
model deploying on multi cards work well

**Comment by mrwyattii** [comment]
@zhaotyer Thank you for reporting this bug. Could you please tell me if you see the same problem when you remove `"deploy_rank": [0,1]` from the `mii_config`?
