### ISSUE TITLE
Run mii-sd.py failed

### ISSUE THREAD

**Issue by 15925473068** [microsoft/DeepSpeed-MII#188]
Hello, I encountered the following error while running mii-sd.py. How can I resolve it.Thank you
deepspeed                0.9.0
deepspeed-mii            0.0.3
urllib3                  1.26.13

Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/root/miniconda3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/root/miniconda3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/root/miniconda3/lib/python3.10/site-packages/urllib3/connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "/root/miniconda3/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/root/miniconda3/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/root/miniconda3/lib/python3.10/ssl.py", line 512, in wrap_socket
    return self.sslsocket_class._create(
  File "/root/miniconda3/lib/python3.10/ssl.py", line 1070, in _create
    self.do_handshake()
  File "/root/miniconda3/lib/python3.10/ssl.py", line 1341, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/root/miniconda3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/root/miniconda3/lib/python3.10/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/root/miniconda3/lib/python3.10/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/root/miniconda3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/root/miniconda3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/root/miniconda3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/root/miniconda3/lib/python3.10/site-packages/urllib3/connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "/root/miniconda3/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/root/miniconda3/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/root/miniconda3/lib/python3.10/ssl.py", line 512, in wrap_socket
    return self.sslsocket_class._create(
  File "/root/miniconda3/lib/python3.10/ssl.py", line 1070, in _create
    self.do_handshake()
  File "/root/miniconda3/lib/python3.10/ssl.py", line 1341, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/DeepSpeed-MII-main/examples/benchmark/txt2img/mii-sd.py", line 15, in <module>
    mii.deploy(task='text-to-image',
  File "/root/miniconda3/lib/python3.10/site-packages/mii/deployment.py", line 82, in deploy
    mii.utils.check_if_task_and_model_is_valid(task, model)
  File "/root/miniconda3/lib/python3.10/site-packages/mii/utils.py", line 120, in check_if_task_and_model_is_valid
    valid_task_models = _get_hf_models_by_type(None, task_name)
  File "/root/miniconda3/lib/python3.10/site-packages/mii/utils.py", line 80, in _get_hf_models_by_type
    models = api.list_models(filter=model_type)
  File "/root/miniconda3/lib/python3.10/site-packages/huggingface_hub/utils/_deprecation.py", line 153, in inner_f
    list_value = f(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 120, in _inner_fn
    return fn(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/huggingface_hub/hf_api.py", line 1055, in list_models
    items = [ModelInfo(**x) for x in data]
  File "/root/miniconda3/lib/python3.10/site-packages/huggingface_hub/hf_api.py", line 1055, in <listcomp>
    items = [ModelInfo(**x) for x in data]
  File "/root/miniconda3/lib/python3.10/site-packages/huggingface_hub/utils/_pagination.py", line 43, in paginate
    r = requests.get(next_page, headers=headers)
  File "/root/miniconda3/lib/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/requests/adapters.py", line 547, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

**Comment by mrwyattii** [comment]
Hi @15925473068 there was bug introduced in DeepSpeed v0.9.0 that broke Stable Diffusion support (https://github.com/microsoft/DeepSpeed/pull/3218). Could you please upgrade to the latest DeepSpeed release and try again? Thanks!

**Comment by 15925473068** [comment]
> 嗨，DeepSpeed v0.9.0中引入了错误，破坏了稳定扩散支持（[Microsoft / DeepSpeed#3218](https://github.com/microsoft/DeepSpeed/pull/3218)）。您能否升级到最新的DeepSpeed版本并重试？谢谢！

Hello, I updated deepspeed=0.9.2, but it's still the same error

**Comment by 15925473068** [comment]
> 嗨，DeepSpeed v0.9.0中引入了错误，破坏了稳定扩散支持（[Microsoft / DeepSpeed#3218](https://github.com/microsoft/DeepSpeed/pull/3218)）。您能否升级到最新的DeepSpeed版本并重试？谢谢！

Hello, I updated deepspeed=0.9.2, but it's still the same error.Thank you!

**Comment by mrwyattii** [comment]
@15925473068 I just tested the script and it's working for me. Can you share the output of `ds_report`? Also, what kind of GPU are you trying to use?

**Comment by mrwyattii** [comment]
Closing. Please reopen if you are still experiencing an issue with the Stable Diffusion models
