### ISSUE TITLE
Chat Session (multi-turn) example is not work.

### ISSUE THREAD

**Issue by jason9693** [microsoft/DeepSpeed-MII#215]
```
[2023-07-31 21:13:49,483] [INFO] [real_accelerator.py:133:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Traceback (most recent call last):
  File "/home/ubuntu/storage/DeepSpeed-MII/examples/local/chat/chat-client-example.py", line 13, in <module>
    generator.create_session(session_id)
  File "/home/ubuntu/storage/DeepSpeed-MII/mii/client.py", line 91, in create_session
    return self.asyncio_loop.run_until_complete(
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/home/ubuntu/storage/DeepSpeed-MII/mii/client.py", line 86, in create_session_async
    return await self.stub.CreateSession(
  File "/opt/conda/lib/python3.9/site-packages/grpc/aio/_call.py", line 290, in __await__
    raise _create_rpc_error(self._cython_call._initial_metadata,
grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
        status = StatusCode.UNKNOWN
        details = "Exception calling application: 'LoadBalancingInterceptor' object has no attribute 'sessions'"
        debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2023-07-31T21:13:49.704422981+00:00", grpc_status:2, grpc_message:"Exception calling application: \'LoadBalancingInterceptor\' object has no attribute \'sessions\'"}"
```

[chat example](https://github.com/microsoft/DeepSpeed-MII/tree/main/examples/local/chat) does not work when try to call `.create_session(session_id)` funtion in [client example.py](https://github.com/microsoft/DeepSpeed-MII/blob/main/examples/local/chat/chat-client-example.py)
It seems 
**LoadBalancingInterceptor** receive wrong attributes.

**Comment by mrwyattii** [comment]
@jason9693 We have merged #217 which fixes this error. Please reopen the issue if it is not fixed. Thanks
