### ISSUE TITLE
Error reasoning about llama2-7b-hf model using MII-Public

### ISSUE THREAD

**Issue by ly19970621** [microsoft/DeepSpeed-MII#226]
I couldn't keep a stable connection with huggingface.co due to network reasons, and I got ConnectionError using the usage example you provided, so I changed the configuration of mii_config with the following code:
```
import mii
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "2"
mii_configs = {"tensor_parallel": 1, "dtype": "fp16", "skip_model_check": True}
mii.deploy(task="text-generation",
            model="./llama2_7b_hf",
            model_path="./llama2_7b_hf",
            deployment_name="llama2_deployment",
            mii_config=mii_configs)

```
After running the above code the following error occurs, the model weights are correct and can be reasoned about, how can I solve the problem?
`FAILED: layer_norm.cuda.o 
/usr/local/cuda/bin/nvcc  -DTORCH_EXTENSION_NAME=transformer_inference -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -I/home/ai_group/anaconda3/envs/liuy/lib/python3.10/site-packages/deepspeed/ops/csrc/transformer/inference/includes -I/home/ai_group/anaconda3/envs/liuy/lib/python3.10/site-packages/deepspeed/ops/csrc/includes -isystem /home/ai_group/anaconda3/envs/liuy/lib/python3.10/site-packages/torch/include -isystem /home/ai_group/anaconda3/envs/liuy/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -isystem /home/ai_group/anaconda3/envs/liuy/lib/python3.10/site-packages/torch/include/TH -isystem /home/ai_group/anaconda3/envs/liuy/lib/python3.10/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /home/ai_group/anaconda3/envs/liuy/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_89,code=compute_89 -gencode=arch=compute_89,code=sm_89 --compiler-options '-fPIC' -std=c++17 -c /home/ai_group/anaconda3/envs/liuy/lib/python3.10/site-packages/deepspeed/ops/csrc/transformer/inference/csrc/layer_norm.cu -o layer_norm.cuda.o 
/home/ai_group/anaconda3/envs/liuy/lib/python3.10/site-packages/deepspeed/ops/csrc/includes/reduction_utils.h(171): error: no operator "+" matches these operands
            operand types are: const __half + const __half
      return lhs + rhs;
                 ^

/home/ai_group/anaconda3/envs/liuy/lib/python3.10/site-packages/deepspeed/ops/csrc/includes/reduction_utils.h(181): error: no operator ">" matches these operands
            operand types are: const __half > const __half
      return (lhs > rhs) ? lhs : rhs;
                  ^

/home/ai_group/anaconda3/envs/liuy/lib/python3.10/site-packages/deepspeed/ops/csrc/includes/reduction_utils.h(192): error: no operator "<" matches these operands
            operand types are: const __half < const __half
      return (lhs < rhs) ? lhs : rhs;
                  ^

/home/ai_group/anaconda3/envs/liuy/lib/python3.10/site-packages/deepspeed/ops/csrc/includes/reduction_utils.h(200): error: no operator "+" matches these operands
            operand types are: const __half2 + const __half2
      return lhs + rhs;
                 ^

/home/ai_group/anaconda3/envs/liuy/lib/python3.10/site-packages/deepspeed/ops/csrc/includes/reduction_utils.h(210): error: no operator ">" matches these operands
            operand types are: const __half > const __half
      ret_val.x = (lhs.x > rhs.x) ? lhs.x : rhs.x;
                         ^

/home/ai_group/anaconda3/envs/liuy/lib/python3.10/site-packages/deepspeed/ops/csrc/includes/reduction_utils.h(211): error: no operator ">" matches these operands
            operand types are: const __half > const __half
      ret_val.y = (lhs.y > rhs.y) ? lhs.y : rhs.y;
                         ^

/home/ai_group/anaconda3/envs/liuy/lib/python3.10/site-packages/deepspeed/ops/csrc/includes/reduction_utils.h(223): error: no operator "<" matches these operands
            operand types are: const __half < const __half
      ret_val.x = (lhs.x < rhs.x) ? lhs.x : rhs.x;
                         ^

/home/ai_group/anaconda3/envs/liuy/lib/python3.10/site-packages/deepspeed/ops/csrc/includes/reduction_utils.h(224): error: no operator "<" matches these operands
            operand types are: const __half < const __half
      ret_val.y = (lhs.y < rhs.y) ? lhs.y : rhs.y;
`

Also FAILED: rms_norm.cuda.o , FAILED: gelu.cuda.o 
Here are more error messages

`ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/ai_group/anaconda3/envs/liuy/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1893, in _run_ninja_build
    subprocess.run(
  File "/home/ai_group/anaconda3/envs/liuy/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ai_group/anaconda3/envs/liuy/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/ai_group/anaconda3/envs/liuy/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/ai_group/anaconda3/envs/liuy/lib/python3.10/site-packages/mii/launch/multi_gpu_server.py", line 70, in <module>
    main()
  File "/home/ai_group/anaconda3/envs/liuy/lib/python3.10/site-packages/mii/launch/multi_gpu_server.py", line 56, in main
    inference_pipeline = load_models(task_name=args.task_name,
  File "/home/ai_group/anaconda3/envs/liuy/lib/python3.10/site-packages/mii/models/load_models.py", line 83, in load_models
    engine = deepspeed.init_inference(getattr(inference_pipeline,
  File "/home/ai_group/anaconda3/envs/liuy/lib/python3.10/site-packages/deepspeed/__init__.py", line 342, in init_inference
    engine = InferenceEngine(model, config=ds_inference_config)
  File "/home/ai_group/anaconda3/envs/liuy/lib/python3.10/site-packages/deepspeed/inference/engine.py", line 192, in __init__
    self._apply_injection_policy(config)
  File "/home/ai_group/anaconda3/envs/liuy/lib/python3.10/site-packages/deepspeed/inference/engine.py", line 426, in _apply_injection_policy
    replace_transformer_layer(client_module, self.module, checkpoint, config, self.config)
  File "/home/ai_group/anaconda3/envs/liuy/lib/python3.10/site-packages/deepspeed/module_inject/replace_module.py", line 523, in replace_transformer_layer
    replaced_module = replace_module(model=model,
  File "/home/ai_group/anaconda3/envs/liuy/lib/python3.10/site-packages/deepspeed/module_inject/replace_module.py", line 766, in replace_module
    replaced_module, _ = _replace_module(model, policy, state_dict=sd)
  File "/home/ai_group/anaconda3/envs/liuy/lib/python3.10/site-packages/deepspeed/module_inject/replace_module.py", line 847, in _replace_module
    _, layer_id = _replace_module(child,
  File "/home/ai_group/anaconda3/envs/liuy/lib/python3.10/site-packages/deepspeed/module_inject/replace_module.py", line 847, in _replace_module
    _, layer_id = _replace_module(child,
  File "/home/ai_group/anaconda3/envs/liuy/lib/python3.10/site-packages/deepspeed/module_inject/replace_module.py", line 823, in _replace_module
    replaced_module = policies[child.__class__][0](child,
  File "/home/ai_group/anaconda3/envs/liuy/lib/python3.10/site-packages/deepspeed/module_inject/replace_module.py", line 500, in replace_fn
    new_module = replace_with_policy(child,
  File "/home/ai_group/anaconda3/envs/liuy/lib/python3.10/site-packages/deepspeed/module_inject/replace_module.py", line 348, in replace_with_policy
    _container.create_module()
  File "/home/ai_group/anaconda3/envs/liuy/lib/python3.10/site-packages/deepspeed/module_inject/containers/llama.py", line 36, in create_module
    self.module = DeepSpeedGPTInference(_config, mp_group=self.mp_group)
  File "/home/ai_group/anaconda3/envs/liuy/lib/python3.10/site-packages/deepspeed/model_implementations/transformers/ds_gpt.py", line 20, in __init__
    super().__init__(config, mp_group, quantize_scales, quantize_groups, merge_count, mlp_extra_grouping)
  File "/home/ai_group/anaconda3/envs/liuy/lib/python3.10/site-packages/deepspeed/model_implementations/transformers/ds_transformer.py", line 58, in __init__
    inference_module = builder.load()
  File "/home/ai_group/anaconda3/envs/liuy/lib/python3.10/site-packages/deepspeed/ops/op_builder/builder.py", line 454, in load
    return self.jit_load(verbose)
  File "/home/ai_group/anaconda3/envs/liuy/lib/python3.10/site-packages/deepspeed/ops/op_builder/builder.py", line 497, in jit_load
    op_module = load(name=self.name,
  File "/home/ai_group/anaconda3/envs/liuy/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1284, in load
    return _jit_compile(
  File "/home/ai_group/anaconda3/envs/liuy/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1509, in _jit_compile
    _write_ninja_file_and_build_library(
  File "/home/ai_group/anaconda3/envs/liuy/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1624, in _write_ninja_file_and_build_library
    _run_ninja_build(
  File "/home/ai_group/anaconda3/envs/liuy/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1909, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension 'transformer_inference'
[2023-08-16 09:57:07,344] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 658717
[2023-08-16 09:57:07,345] [ERROR] [launch.py:321:sigkill_handler] ['/home/ai_group/anaconda3/envs/liuy/bin/python', '-m', 'mii.launch.multi_gpu_server', '--task-name', 'text-generation', '--model', './llama2-7b-hf', '--model-path', './llama2-7b-hf', '--port', '50050', '--ds-optimize', '--provider', 'hugging-face', '--config', 'eyJ0ZW5zb3JfcGFyYWxsZWwiOiAxLCAicG9ydF9udW1iZXIiOiA1MDA1MCwgImR0eXBlIjogInRvcmNoLmZsb2F0MTYiLCAibG9hZF93aXRoX3N5c19tZW0iOiBmYWxzZSwgImVuYWJsZV9jdWRhX2dyYXBoIjogZmFsc2UsICJjaGVja3BvaW50X2RpY3QiOiBudWxsLCAiZGVwbG95X3JhbmsiOiBbMF0sICJ0b3JjaF9kaXN0X3BvcnQiOiAyOTUwMCwgImhmX2F1dGhfdG9rZW4iOiBudWxsLCAicmVwbGFjZV93aXRoX2tlcm5lbF9pbmplY3QiOiB0cnVlLCAicHJvZmlsZV9tb2RlbF90aW1lIjogZmFsc2UsICJza2lwX21vZGVsX2NoZWNrIjogdHJ1ZX0='] exits with return code = 1
[2023-08-16 09:57:08,539] [INFO] [server_client.py:117:_wait_until_server_is_live] waiting for server to start...
Traceback (most recent call last):
  File "/home/ai_group/liuy/test_mii.py", line 9, in <module>
    mii.deploy(task="text-generation",
  File "/home/ai_group/anaconda3/envs/liuy/lib/python3.10/site-packages/mii/deployment.py", line 114, in deploy
    return _deploy_local(deployment_name, model_path=model_path)
  File "/home/ai_group/anaconda3/envs/liuy/lib/python3.10/site-packages/mii/deployment.py", line 120, in _deploy_local
    mii.utils.import_score_file(deployment_name).init()
  File "/tmp/mii_cache/llama2_deployment/score.py", line 30, in init
    model = mii.MIIServerClient(task,
  File "/home/ai_group/anaconda3/envs/liuy/lib/python3.10/site-packages/mii/server_client.py", line 92, in __init__
    self._wait_until_server_is_live()
  File "/home/ai_group/anaconda3/envs/liuy/lib/python3.10/site-packages/mii/server_client.py", line 115, in _wait_until_server_is_live
    raise RuntimeError("server crashed for some reason, unable to proceed")
RuntimeError: server crashed for some reason, unable to proceed
`

**Comment by mrwyattii** [comment]
Hi @ly19970621, this looks like an issue with the kernel compilation happening with DeepSpeed-Inference. Can you please share the output of `ds_report` and also try pre-compiling the kernels with `DS_BUILD_TRANSFORMER_INFERENCE=1 pip install deepspeed` and share the result? Thanks

**Comment by ly19970621** [comment]
> Hi @ly19970621, this looks like an issue with the kernel compilation happening with DeepSpeed-Inference. Can you please share the output of `ds_report` and also try pre-compiling the kernels with `DS_BUILD_TRANSFORMER_INFERENCE=1 pip install deepspeed` and share the result? Thanks

Thanks for the reply.I ran ```python -m deepspeed.env_report``` and here is the output:

```python -m deepspeed.env_report
[2023-08-18 01:26:20,378] [INFO] [real_accelerator.py:133:get_accelerator] Setting ds_accelerator to cuda (auto detect)
--------------------------------------------------
DeepSpeed C++/CUDA extension op report
--------------------------------------------------
NOTE: Ops not installed will be just-in-time (JIT) compiled at
      runtime if needed. Op compatibility means that your system
      meet the required dependencies to JIT install the op.
--------------------------------------------------
JIT compiled ops requires ninja
ninja .................. [OKAY]
--------------------------------------------------
op name ................ installed .. compatible
--------------------------------------------------
async_io ............... [NO] ....... [OKAY]
cpu_adagrad ............ [NO] ....... [OKAY]
cpu_adam ............... [NO] ....... [OKAY]
fused_adam ............. [NO] ....... [OKAY]
fused_lamb ............. [NO] ....... [OKAY]
quantizer .............. [NO] ....... [OKAY]
random_ltd ............. [NO] ....... [OKAY]
 [WARNING]  sparse_attn requires a torch version >= 1.5 and < 2.0 but detected 2.0
 [WARNING]  using untested triton version (2.0.0), only 1.0.0 is known to be compatible
sparse_attn ............ [NO] ....... [NO]
spatial_inference ...... [NO] ....... [OKAY]
transformer ............ [NO] ....... [OKAY]
stochastic_transformer . [NO] ....... [OKAY]
transformer_inference .. [NO] ....... [OKAY]
--------------------------------------------------
DeepSpeed general environment info:
torch install path ............... ['/home/ai_group/anaconda3/envs/liuy026/lib/python3.10/site-packages/torch']
torch version .................... 2.0.1+cu118
deepspeed install path ........... ['/home/ai_group/anaconda3/envs/liuy026/lib/python3.10/site-packages/deepspeed']
deepspeed info ................... 0.10.0, unknown, unknown
torch cuda version ............... 11.8
torch hip version ................ None
nvcc version ..................... 12.2
deepspeed wheel compiled w. ...... torch 2.0, cuda 11.8
```
I ran ```DS_BUILD_TRANSFORMER_INFERENCE=1 pip install deepspeed``` and the environment didn't change, re-executing it still gives the above error

**Comment by mrwyattii** [comment]
@ly19970621 sorry for the lack of timely response. If you are still experiencing this error, could you please try to run the following script with just DeepSpeed and share the results?
```python
import torch
import deepspeed
import os
import time
from transformers import pipeline

local_rank = int(os.getenv("LOCAL_RANK", "0"))
world_size = int(os.getenv("WORLD_SIZE", "1"))

task_name = "text-generation"
model_name_or_path = "./llama2_7b_hf"
input_strs = ["DeepSpeed is", "Microsoft is"]

def run():
    pipe = pipeline(task_name, model_name_or_path, torch_dtype=torch.float16, device=local_rank)

    pipe.model = deepspeed.init_inference(
        pipe.model,
        replace_with_kernel_inject=True,
        mp_size=world_size,
        dtype=torch.float16,
    )

    output = pipe(input_strs)
    print(output)

if __name__ == "__main__":
    run()
```

Run this with `deepspeed llama-example.py`

**Comment by muhammad-asn** [comment]
@ly19970621 any update on this sir? I try to run llama-2-13b-chat-hf with T4 (4 x 16 GB) GPU and still got this.
Cc: @mrwyattii
