### ISSUE TITLE
DeepSpeed MII Serve error on V100

### ISSUE THREAD

**Issue by amazingkmy** [microsoft/DeepSpeed-MII#263]
[WARNING]  Filtered compute capabilities ['7.0+PTX']
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.10/site-packages/deepspeed_mii-0.1.1+32ea708-py3.10.egg/mii/launch/multi_gpu_server.py", line 97, in <module>
    main()
  File "/opt/conda/lib/python3.10/site-packages/deepspeed_mii-0.1.1+32ea708-py3.10.egg/mii/launch/multi_gpu_server.py", line 90, in main
    inference_pipeline = async_pipeline(args.model_config)
  File "/opt/conda/lib/python3.10/site-packages/deepspeed_mii-0.1.1+32ea708-py3.10.egg/mii/pipeline.py", line 41, in async_pipeline
    inference_engine = load_model(model_config)
  File "/opt/conda/lib/python3.10/site-packages/deepspeed_mii-0.1.1+32ea708-py3.10.egg/mii/models.py", line 17, in load_model
    inference_engine = build_hf_engine(
  File "/opt/conda/lib/python3.10/site-packages/deepspeed/inference/v2/engine_factory.py", line 46, in build_hf_engine
    return InferenceEngineV2(policy, engine_config)
  File "/opt/conda/lib/python3.10/site-packages/deepspeed/inference/v2/engine_v2.py", line 65, in __init__
    self._model = self._policy.build_model(self._config, self._base_mp_group)
  File "/opt/conda/lib/python3.10/site-packages/deepspeed/inference/v2/model_implementations/inference_policy_base.py", line 110, in build_model
    self.model = self.instantiate_model(engine_config, mp_group)
  File "/opt/conda/lib/python3.10/site-packages/deepspeed/inference/v2/model_implementations/mistral/policy.py", line 23, in instantiate_model
    return MistralInferenceModel(config=self._model_config, engine_config=engine_config, base_mp_group=mp_group)
  File "/opt/conda/lib/python3.10/site-packages/deepspeed/inference/v2/model_implementations/inference_transformer_base.py", line 229, in __init__
    self.make_attn_layer()
  File "/opt/conda/lib/python3.10/site-packages/deepspeed/inference/v2/model_implementations/inference_transformer_base.py", line 346, in make_attn_layer
    self.attn = heuristics.instantiate_attention(attn_config, self._engine_config)
  File "/opt/conda/lib/python3.10/site-packages/deepspeed/inference/v2/modules/heuristics.py", line 53, in instantiate_attention
    return DSSelfAttentionRegistry.instantiate_config(config)
  File "/opt/conda/lib/python3.10/site-packages/deepspeed/inference/v2/modules/module_registry.py", line 39, in instantiate_config
    return cls.registry[config_bundle.name](config_bundle.config, config_bundle.implementation_config)
  File "/opt/conda/lib/python3.10/site-packages/deepspeed/inference/v2/modules/implementations/attention/dense_blocked_attention.py", line 88, in __init__
    self._kv_copy = BlockedRotaryEmbeddings(self._config.head_size, self._config.n_heads_q,
  File "/opt/conda/lib/python3.10/site-packages/deepspeed/inference/v2/kernels/ragged_ops/linear_blocked_kv_rotary/blocked_kv_rotary.py", line 49, in __init__
    inf_module = RaggedOpsBuilder().load()
  File "/opt/conda/lib/python3.10/site-packages/deepspeed/ops/op_builder/builder.py", line 452, in load
    return self.jit_load(verbose)
  File "/opt/conda/lib/python3.10/site-packages/deepspeed/ops/op_builder/builder.py", line 488, in jit_load
    nvcc_args = self.strip_empty_entries(self.nvcc_args())
  File "/opt/conda/lib/python3.10/site-packages/deepspeed/ops/op_builder/builder.py", line 689, in nvcc_args
    args += self.compute_capability_args()
  File "/opt/conda/lib/python3.10/site-packages/deepspeed/ops/op_builder/builder.py", line 569, in compute_capability_args
    raise RuntimeError(
RuntimeError: Unable to load ragged_device_ops op due to no compute capabilities remaining after filtering

mii doesn't support V100?

**Comment by mrwyattii** [comment]
Hi @amazingkmy - The latest changes to support DeepSpeed-FastGen in MII are only supported on CUDA compute capabilities 8.0+ (i.e., Ampere+) which does not include the V100. We still offer support for V100 through [MII-Legacy](https://github.com/microsoft/DeepSpeed-MII#mii-legacy) for accelerating your models!

**Comment by bibo-msft** [comment]
I am facing the same issue. Is there an example of using MII-Legacy APIs?

**Comment by bibo-msft** [comment]
https://github.com/microsoft/DeepSpeed-MII/tree/main/tests/legacy
Here are examples of calling the MII-Legacy APIs.

**Comment by mrwyattii** [comment]
> I am facing the same issue. Is there an example of using MII-Legacy APIs?

@bibo-msft here is the MII-Legacy landing pages, with docs and examples: https://github.com/microsoft/DeepSpeed-MII/tree/main/mii/legacy
