### ISSUE TITLE
Why generation_config.json is a requirement for start server?

### ISSUE THREAD

**Issue by flexwang** [microsoft/DeepSpeed-MII#287]
I was following the example in DeepSpeedExamples and run `python server.py --model_name /models/llama-2-70b-chat-hf -m 8 -b 1024 start` and see below error. 
I was wondering, why generation config is a must for start a model serving?
```
OSError: /models/llama-2-70b-chat-hf does not appear to have a file named generation_config.json. Checkout 'https://huggingface.co//models/llama-2-70b-chat-hf/main' for available files.
```

**Comment by mrwyattii** [comment]
Hi @flexwang can you share the full stack trace for this error? I'm guessing it is coming from `transformers` at this line?
https://github.com/microsoft/DeepSpeed/blob/6ea44d02c674393c524ada811ea376c55438a913/deepspeed/inference/v2/checkpoint/huggingface_engine.py#L24

**Comment by sfc-gh-zhwang** [comment]
@mrwyattii 
Here you are:
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/corvo/.local/lib/python3.10/site-packages/mii/launch/multi_gpu_server.py", line 97, in <module>
    main()
  File "/home/corvo/.local/lib/python3.10/site-packages/mii/launch/multi_gpu_server.py", line 90, in main
    inference_pipeline = async_pipeline(args.model_config)
  File "/home/corvo/.local/lib/python3.10/site-packages/mii/api.py", line 170, in async_pipeline
    inference_engine = load_model(model_config)
  File "/home/corvo/.local/lib/python3.10/site-packages/mii/modeling/models.py", line 17, in load_model
    inference_engine = build_hf_engine(
  File "/home/corvo/.local/lib/python3.10/site-packages/deepspeed/inference/v2/engine_factory.py", line 27, in build_hf_engine
    checkpoint_engine = HuggingFaceCheckpointEngine(path)
  File "/home/corvo/.local/lib/python3.10/site-packages/deepspeed/inference/v2/checkpoint/huggingface_engine.py", line 24, in __init__
    self.generation_config = GenerationConfig.from_pretrained(self.model_name_or_path)
  File "/home/corvo/.local/lib/python3.10/site-packages/transformers/generation/configuration_utils.py", line 711, in from_pretrained
    resolved_config_file = cached_file(
  File "/home/corvo/.local/lib/python3.10/site-packages/transformers/utils/hub.py", line 401, in cached_file
    raise EnvironmentError(
OSError: /models/llama-2-70b-chat-hf does not appear to have a file named generation_config.json. Checkout 'https://huggingface.co//models/llama-2-70b-chat-hf/main' for available files.
```

**Comment by flexwang** [comment]
@mrwyattii, I think you are right
Here you are:
```

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/corvo/.local/lib/python3.10/site-packages/mii/launch/multi_gpu_server.py", line 97, in <module>
    main()
  File "/home/corvo/.local/lib/python3.10/site-packages/mii/launch/multi_gpu_server.py", line 90, in main
    inference_pipeline = async_pipeline(args.model_config)
  File "/home/corvo/.local/lib/python3.10/site-packages/mii/api.py", line 170, in async_pipeline
    inference_engine = load_model(model_config)
  File "/home/corvo/.local/lib/python3.10/site-packages/mii/modeling/models.py", line 17, in load_model
    inference_engine = build_hf_engine(
  File "/home/corvo/.local/lib/python3.10/site-packages/deepspeed/inference/v2/engine_factory.py", line 27, in build_hf_engine
    checkpoint_engine = HuggingFaceCheckpointEngine(path)
  File "/home/corvo/.local/lib/python3.10/site-packages/deepspeed/inference/v2/checkpoint/huggingface_engine.py", line 24, in __init__
    self.generation_config = GenerationConfig.from_pretrained(self.model_name_or_path)
  File "/home/corvo/.local/lib/python3.10/site-packages/transformers/generation/configuration_utils.py", line 711, in from_pretrained
    resolved_config_file = cached_file(
  File "/home/corvo/.local/lib/python3.10/site-packages/transformers/utils/hub.py", line 401, in cached_file
    raise EnvironmentError(
OSError: /models/llama-2-70b-chat-hf does not appear to have a file named generation_config.json. Checkout 'https://huggingface.co//models/llama-2-70b-chat-hf/main' for available files.
```

**Comment by mrwyattii** [comment]
@flexwang can you download the config files from HF and add to your local directory? Specifically, this file: https://huggingface.co/meta-llama/Llama-2-70b-chat-hf/blob/main/generation_config.json

**Comment by flexwang** [comment]
yeah, that's how I mitigate the issue. But my question is that file shouldn't be a requirement because we are passing generation config through `generate` function anyway.

**Comment by mrwyattii** [comment]
I see - it looks like we are only ever using the generation config to set `max_seq_length`. I'm sure we could find a way to avoid the generation_config.json being necessary. I'll get back to you soon with a solution!

**Comment by mrwyattii** [comment]
This problem should now be fixed. Please update to the latest DS `pip install git+https://github.com/Microsoft/DeepSpeed`
