### ISSUE TITLE
Non deterministic generation result from the same prompt

### ISSUE THREAD

**Issue by flexwang** [microsoft/DeepSpeed-MII#288]
Should deepspeed mii give the same result with the same prompt when setting `topp=1.0, temperature=1.0`? I run below code to generate response for the same prompt twice, and the result are different for the same prompt. Model is `llama2-70b-chat-hf`
```
    client = mii.client("benchmark")
    prompt = '''<s>[INST]<<SYS>>
    Please summarize the text that is given. Return just the summary and no additional conversational dialog such as "Sure, here is the summary of the text:".
    <</SYS>> dr. goldberg offers everything i look for in a general practitioner.  he's nice and easy to talk to without being patronizing; he's always on time in seeing his patients; he's affiliated with a top-notch hospital (nyu) which my parents have explained to me is very important in case something happens and you need surgery; and you can get referrals to see specialists without having to see him first.  really, what more do you need?  i'm sitting here trying to think of any complaints i have about him, but i'm really drawing a blank.[/INST]'''
    result = client.generate(
        [prompt, prompt], max_new_tokens=512, top_p=1.0, temperature=1.0)
    for i in result.response:
        print(i)
```
Result is
```
 Dr. Goldberg is a good general practitioner because he is friendly and punctual, affiliated with a reputable hospital, and provides convenient access to specialists.
 Dr. Goldberg is a general practitioner who is well-liked for his pleasant and respectful demeanor, punctuality, and affiliation with a reputable hospital. He also offers convenient referrals to specialists. The writer cannot think of any complaints about him.
```

**Comment by mrwyattii** [comment]
You will also need to set `do_sample=False` in your `generate()` call.

**Comment by flexwang** [comment]
Doesn't seem that `do_sample` is supported?
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/corvo/DeepSpeedExamples/benchmarks/inference/mii/run_benchmark_client.py", line 244, in _run_parallel
    call_mii_bulk(client, query_queue, result_queue)
  File "/home/corvo/DeepSpeedExamples/benchmarks/inference/mii/run_benchmark_client.py", line 83, in call_mii_bulk
    result = client.generate(
  File "/home/corvo/.local/lib/python3.10/site-packages/mii/backend/client.py", line 73, in generate
    return self.asyncio_loop.run_until_complete(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/corvo/.local/lib/python3.10/site-packages/mii/backend/client.py", line 46, in _request_async_response
    proto_response = await getattr(self.stub, task_methods.method)(proto_request)
  File "/home/corvo/.local/lib/python3.10/site-packages/grpc/aio/_call.py", line 318, in __await__
    raise _create_rpc_error(
grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Exception calling application: <AioRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Exception calling application: Unknown keyword arguments {'do_sample': False}"
	debug_error_string = "UNKNOWN:Error received from peer ipv6:%5B::1%5D:50051 {grpc_message:"Exception calling application: Unknown keyword arguments {\'do_sample\': False}", grpc_status:2, created_time:"2023-11-13T16:52:07.226715075+00:00"}"
>"
	debug_error_string = "UNKNOWN:Error received from peer ipv6:%5B::1%5D:50050 {created_time:"2023-11-13T16:52:07.229221268+00:00", grpc_status:2, grpc_message:"Exception calling application: <AioRpcError of RPC that terminated with:\n\tstatus = StatusCode.UNKNOWN\n\tdetails = \"Exception calling application: Unknown keyword arguments {\'do_sample\': False}\"\n\tdebug_error_string = \"UNKNOWN:Error received from peer ipv6:%5B::1%5D:50051 {grpc_message:\"Exception calling application: Unknown keyword arguments {\\\'do_sample\\\': False}\", grpc_status:2, created_time:\"2023-11-13T16:52:07.226715075+00:00\"}\"\n>"}"
```

**Comment by mrwyattii** [comment]
Can you update your DeepSpeed-MII to the latest release? `pip install deepspeed-mii==0.1.1`

This option was only added in #280
