### ISSUE TITLE
TypeError: cannot unpack non-iterable Response object

### ISSUE THREAD

**Issue by flexwang** [microsoft/DeepSpeed-MII#289]
Encountered error when I run below code
```
        result = client.generate(
            prompts, max_new_tokens=512, top_p=1.0, temperature=1.0)
```
Detailed stack is below, but I am still able to get result and print it - it's just the error message being concerning.
```
Traceback (most recent call last):
  File "/home/corvo/.local/lib/python3.10/site-packages/grpc/_server.py", line 552, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "/home/corvo/.local/lib/python3.10/site-packages/mii/grpc_related/modelresponse_server.py", line 98, in GeneratorReply
    return self._run_inference("GeneratorReply", request)
  File "/home/corvo/.local/lib/python3.10/site-packages/mii/grpc_related/modelresponse_server.py", line 80, in _run_inference
    uid, response = self.inference_pipeline.get_response()
TypeError: cannot unpack non-iterable Response object
Traceback (most recent call last):
  File "/home/corvo/.local/lib/python3.10/site-packages/grpc/_server.py", line 552, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "/home/corvo/.local/lib/python3.10/site-packages/mii/grpc_related/modelresponse_server.py", line 98, in GeneratorReply
    return self._run_inference("GeneratorReply", request)
  File "/home/corvo/.local/lib/python3.10/site-packages/mii/grpc_related/modelresponse_server.py", line 80, in _run_inference
    uid, response = self.inference_pipeline.get_response()
TypeError: cannot unpack non-iterable Response object
Traceback (most recent call last):
  File "/home/corvo/.local/lib/python3.10/site-packages/grpc/_server.py", line 552, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "/home/corvo/.local/lib/python3.10/site-packages/mii/grpc_related/modelresponse_server.py", line 98, in GeneratorReply
    return self._run_inference("GeneratorReply", request)
  File "/home/corvo/.local/lib/python3.10/site-packages/mii/grpc_related/modelresponse_server.py", line 80, in _run_inference
    uid, response = self.inference_pipeline.get_response()
TypeError: cannot unpack non-iterable Response object
Traceback (most recent call last):
  File "/home/corvo/.local/lib/python3.10/site-packages/grpc/_server.py", line 552, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "/home/corvo/.local/lib/python3.10/site-packages/mii/grpc_related/modelresponse_server.py", line 98, in GeneratorReply
    return self._run_inference("GeneratorReply", request)
  File "/home/corvo/.local/lib/python3.10/site-packages/mii/grpc_related/modelresponse_server.py", line 80, in _run_inference
    uid, response = self.inference_pipeline.get_response()
TypeError: cannot unpack non-iterable Response object
Traceback (most recent call last):
  File "/home/corvo/.local/lib/python3.10/site-packages/grpc/_server.py", line 552, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "/home/corvo/.local/lib/python3.10/site-packages/mii/grpc_related/modelresponse_server.py", line 98, in GeneratorReply
    return self._run_inference("GeneratorReply", request)
  File "/home/corvo/.local/lib/python3.10/site-packages/mii/grpc_related/modelresponse_server.py", line 80, in _run_inference
    uid, response = self.inference_pipeline.get_response()
TypeError: cannot unpack non-iterable Response object
Traceback (most recent call last):
  File "/home/corvo/.local/lib/python3.10/site-packages/grpc/_server.py", line 552, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "/home/corvo/.local/lib/python3.10/site-packages/mii/grpc_related/modelresponse_server.py", line 98, in GeneratorReply
    return self._run_inference("GeneratorReply", request)
  File "/home/corvo/.local/lib/python3.10/site-packages/mii/grpc_related/modelresponse_server.py", line 80, in _run_inference
    uid, response = self.inference_pipeline.get_response()
TypeError: cannot unpack non-iterable Response object
Traceback (most recent call last):
  File "/home/corvo/.local/lib/python3.10/site-packages/grpc/_server.py", line 552, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "/home/corvo/.local/lib/python3.10/site-packages/mii/grpc_related/modelresponse_server.py", line 98, in GeneratorReply
    return self._run_inference("GeneratorReply", request)
  File "/home/corvo/.local/lib/python3.10/site-packages/mii/grpc_related/modelresponse_server.py", line 80, in _run_inference
    uid, response = self.inference_pipeline.get_response()
TypeError: cannot unpack non-iterable Response object
```

**Comment by flexwang** [comment]
Also, it doesn't happen everytime, seems a bit random

**Comment by easonfzw** [comment]
Same issue, this problem occurs when I start the llamav2-70b model on the server and set tensor_parallel=4, replica_num=1, and call it from the client. Is there a solution? The environment is 4 A100 gpu @mrwyattii

**Comment by mrwyattii** [comment]
@flexwang @easonfzw is this with the latest MII release (v0.1.1)? I thought I had fixed this bug, but I will try to reproduce. Thank you for reporting!

**Comment by sfc-gh-zhwang** [comment]
I built it from source, so it should be ahead of v0.1.1

**Comment by flexwang** [comment]
I built it from source, so it should be ahead of v0.1.1

**Comment by easonfzw** [comment]
use the latest main branch it's ok

**Comment by mrwyattii** [comment]
> I built it from source, so it should be ahead of v0.1.1

@flexwang can you share the commit that you are on? This will help me debug if the issue is persistent on the latest `main`

**Comment by mrwyattii** [comment]
@flexwang please reopen this issue if you are still seeing this error on the latest DeepSpeed-MII. Thanks!
