### ISSUE TITLE
Why did an unknown error occur in gprc calls when enable_restful_api is true 

### ISSUE THREAD

**Issue by wtontheway** [microsoft/DeepSpeed-MII#290]
I don't know the reason why this error occurred。After started the deepspeed service using the following code， using the curl command to call the restful service, then the error occurred。

```
import mii
from mii import DeploymentType

mii_configs = {
    "deployment_type": DeploymentType.LOCAL,
    "enable_restful_api": True,
    "deployment_name": "zzz-mii",

}

model_configs = {
    "replica_num": 1,
    "tensor_parallel": 1,
}

mii.serve("/mnt/home/LlaMa2/file",
          model_config=model_configs,
          mii_config=mii_configs, )
```

```
root@ctm:/mnt/home/zzz/mii-test# curl  -X POST  -H "Content-Type: application/json" -d '{"request": {"query": "DeepSpeed is the greatest"}}' http://localhost:51080/mii/zzz-mii
[2023-11-13 15:46:45,323] ERROR in app: Exception on /mii/zzz-mii [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/usr/local/lib/python3.8/dist-packages/flask_restful/__init__.py", line 489, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flask/views.py", line 109, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flask_restful/__init__.py", line 604, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/mii/grpc_related/restful_gateway.py", line 31, in post
    result = client.query(data["request"], **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/mii/legacy/client.py", line 77, in query
    return self.asyncio_loop.run_until_complete(
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.8/dist-packages/mii/legacy/client.py", line 73, in _request_async_response
    proto_response = await getattr(self.stub, task_methods.method)(proto_request)
  File "/usr/local/lib/python3.8/dist-packages/grpc/aio/_call.py", line 306, in __await__
    raise _create_rpc_error(
grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
        status = StatusCode.UNKNOWN
        details = "Error in service handler!"
        debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"Error in service handler!", grpc_status:2, created_time:"2023-11-13T15:46:45.322701634+08:00"}"
>
127.0.0.1 - - [13/Nov/2023 15:46:45] "POST /mii/zzz-mii HTTP/1.1" 500 -
```

**Comment by wtontheway** [comment]
@mrwyattii could you help me, please  😭😭

**Comment by mrwyattii** [comment]
Hi @wtontheway we are still working on bringing the restful API into the latest release of MII. Look for updates later this week that will fix this functionality. Thanks!

**Comment by mrwyattii** [comment]
Please see the example we have for enabling the REST API: https://github.com/microsoft/DeepSpeed-MII#restful-api

You will need to install from source until we do our next release: `pip install git+https://github.com/microsoft/DeepSpeed-MII.git`

**Comment by wtontheway** [comment]
> Please see the example we have for enabling the REST API: https://github.com/microsoft/DeepSpeed-MII#restful-api
> 
> You will need to install from source until we do our next release: `pip install git+https://github.com/microsoft/DeepSpeed-MII.git`

Thank you very much for resolving this issue! I am truly grateful for your assistance.

**Comment by wtontheway** [comment]
> Hi @wtontheway we are still working on bringing the restful API into the latest release of MII. Look for updates later this week that will fix this functionality. Thanks!

Thank you very much for resolving this issue! I am truly grateful for your assistance.
