### ISSUE TITLE
RuntimeError: There is no current event loop in thread 'Thread-1'.

### ISSUE THREAD

**Issue by 4thGardenOfQMH** [microsoft/DeepSpeed-MII#341]
hi,when i run the newes code,i went this error
` [2023-12-04 14:13:53,746] ERROR in app: Exception on /mii/my-mii [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/usr/local/lib/python3.8/dist-packages/flask_restful/__init__.py", line 489, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flask/views.py", line 106, in view
    self = view.view_class(  # type: ignore[attr-defined]
  File "/usr/local/lib/python3.8/dist-packages/mii/grpc_related/restful_gateway.py", line 25, in __init__
    self.client = mii.client(deployment_name)
  File "/usr/local/lib/python3.8/dist-packages/mii/api.py", line 102, in client
    return MIIClient(mii_config)
  File "/usr/local/lib/python3.8/dist-packages/mii/backend/client.py", line 36, in __init__
    self.asyncio_loop = asyncio.get_event_loop()
  File "/usr/lib/python3.8/asyncio/events.py", line 639, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'Thread-1'.
127.0.0.1 - - [04/Dec/2023 14:13:53] "POST /mii/zte-mii HTTP/1.1" 500 -
`

my code:
`import mii
from mii import DeploymentType

mii_configs = {
    "deployment_type": DeploymentType.LOCAL,   
    "enable_restful_api": True,     
    "deployment_name": "my-mii",  
}

model_configs = {
    "replica_num": 1,       
    "tensor_parallel": 1,   
    "torch_dist_port":29501
}

mii.serve("/mnt/home/LlaMa2/file",
          model_config=model_configs,
          mii_config=mii_configs, )`

**Comment by mrwyattii** [comment]
Hi @4thGardenOfQMH what version of `flask` do you have installed? I will try to reproduce the error on my side
