### ISSUE TITLE
Can deepspeed-MII run on AMD GPU?

### ISSUE THREAD

**Issue by sunpian1** [microsoft/DeepSpeed-MII#345]
Can deepspeed-MII run on AMD GPU?

susie.sun@yz-amd1:~$ deepspeed --num_gpus 1 pipe.py
[2023-12-05 09:42:21,499] [INFO] [real_accelerator.py:161:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-12-05 09:42:21,780] [WARNING] [runner.py:203:fetch_hostfile] Unable to find hostfile, will proceed with training with local resources only.
Traceback (most recent call last):
  File "/home/susie.sun/.local/bin/deepspeed", line 6, in <module>
    main()
  File "/home/susie.sun/.local/lib/python3.10/site-packages/deepspeed/launcher/runner.py", line 422, in main
    raise RuntimeError("Unable to proceed, no GPU resources available")
RuntimeError: Unable to proceed, no GPU resources available

susie.sun@yz-amd1:~$ cat pipe.py
import mii
pipe = mii.pipeline("mistralai/Mistral-7B-v0.1")
response = pipe(["DeepSpeed is", "Seattle is"], max_new_tokens=128)
print(response)

**Comment by mrwyattii** [comment]
Hi @sunpian1, our custom kernels do not currently support AMD GPUs. It is something we have considered, and I will share this with the other devs. Thank you!

**Comment by sunpian1** [comment]
@mrwyattii thanks for your answer!
