### ISSUE TITLE
Problem while running facebook/opt-125m with MII

### ISSUE THREAD

**Issue by wangtianxia-sjtu** [microsoft/DeepSpeed-MII#358]
I meet this problem when I am running model facebook/opt-125m with MII. I am using Tesla V100, Driver Version: 470.82.01    CUDA Version: 12.1

```
Python 3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import mii
>>> pipe = mii.pipeline("facebook/opt-125m")
[2023-12-20 08:04:58,943] [INFO] [comm.py:637:init_distributed] cdb=None
[2023-12-20 08:04:58,943] [INFO] [comm.py:668:init_distributed] Initializing TorchBackend in DeepSpeed with backend nccl
Fetching 6 files: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6/6 [00:00<00:00, 54471.48it/s]
[2023-12-20 08:05:00,368] [INFO] [engine_v2.py:82:__init__] Building model...
Using /root/.cache/torch_extensions/py310_cu121 as PyTorch extensions root...
Detected CUDA files, patching ldflags
Emitting ninja build file /root/.cache/torch_extensions/py310_cu121/inference_core_ops/build.ninja...
Building extension module inference_core_ops...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module inference_core_ops...
Time to load inference_core_ops op: 0.11945390701293945 seconds
 [WARNING]  Filtered compute capabilities ['7.0+PTX']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.10/site-packages/mii/api.py", line 159, in pipeline
    inference_engine = load_model(model_config)
  File "/opt/conda/lib/python3.10/site-packages/mii/modeling/models.py", line 17, in load_model
    inference_engine = build_hf_engine(
  File "/opt/conda/lib/python3.10/site-packages/deepspeed/inference/v2/engine_factory.py", line 113, in build_hf_engine
    return InferenceEngineV2(policy, engine_config)
  File "/opt/conda/lib/python3.10/site-packages/deepspeed/inference/v2/engine_v2.py", line 83, in __init__
    self._model = self._policy.build_model(self._config, self._base_mp_group)
  File "/opt/conda/lib/python3.10/site-packages/deepspeed/inference/v2/model_implementations/inference_policy_base.py", line 156, in build_model
    self.model = self.instantiate_model(engine_config, mp_group)
  File "/opt/conda/lib/python3.10/site-packages/deepspeed/inference/v2/model_implementations/opt/policy.py", line 17, in instantiate_model
    return OPTInferenceModel(config=self._model_config, engine_config=engine_config, base_mp_group=mp_group)
  File "/opt/conda/lib/python3.10/site-packages/deepspeed/inference/v2/model_implementations/inference_transformer_base.py", line 208, in __init__
    self.make_attn_layer()
  File "/opt/conda/lib/python3.10/site-packages/deepspeed/inference/v2/model_implementations/inference_transformer_base.py", line 324, in make_attn_layer
    self.attn = heuristics.instantiate_attention(attn_config, self._engine_config)
  File "/opt/conda/lib/python3.10/site-packages/deepspeed/inference/v2/modules/heuristics.py", line 53, in instantiate_attention
    return DSSelfAttentionRegistry.instantiate_config(config)
  File "/opt/conda/lib/python3.10/site-packages/deepspeed/inference/v2/modules/module_registry.py", line 39, in instantiate_config
    return cls.registry[config_bundle.name](config_bundle.config, config_bundle.implementation_config)
  File "/opt/conda/lib/python3.10/site-packages/deepspeed/inference/v2/modules/implementations/attention/dense_blocked_attention.py", line 79, in __init__
    self._kv_copy = LinearBlockedKVCopy(self._config.head_size, self._config.n_heads_q,
  File "/opt/conda/lib/python3.10/site-packages/deepspeed/inference/v2/kernels/ragged_ops/linear_blocked_kv_rotary/linear_blocked_kv_copy.py", line 53, in __init__
    inf_module = RaggedOpsBuilder().load()
  File "/opt/conda/lib/python3.10/site-packages/deepspeed/ops/op_builder/builder.py", line 458, in load
    return self.jit_load(verbose)
  File "/opt/conda/lib/python3.10/site-packages/deepspeed/ops/op_builder/builder.py", line 489, in jit_load
    nvcc_args = self.strip_empty_entries(self.nvcc_args())
  File "/opt/conda/lib/python3.10/site-packages/deepspeed/ops/op_builder/builder.py", line 693, in nvcc_args
    args += self.compute_capability_args()
  File "/opt/conda/lib/python3.10/site-packages/deepspeed/ops/op_builder/builder.py", line 570, in compute_capability_args
    raise RuntimeError(
RuntimeError: Unable to load ragged_device_ops op due to no compute capabilities remaining after filtering
```

**Comment by mrwyattii** [comment]
Hi @wangtianxia-sjtu the V100 is not compatible with the latest MII (e.g.,  FastGen). You need compute capabilities 8.0+ (Ampere+). We still offer support to V100 with [MII-Legacy](https://github.com/microsoft/DeepSpeed-MII/tree/main/mii/legacy) APIs!

**Comment by wangtianxia-sjtu** [comment]
Thank you for the reply! I will try MII-Legacy first.
