### ISSUE TITLE
support for mixtral family ? 

### ISSUE THREAD

**Issue by S-Yacer** [microsoft/DeepSpeed-MII#389]
I have seen earlier issues that suggest support for mixtral models specifically: mistralai/Mixtral-8x7B-v0.1 which indeed works but when using the instruction tuned version of the model: mistralai/Mixtral-8x7B-Instruct-v0.1 or other finetuned versions such as: NousResearch/Nous-Hermes-2-Mixtral-8x7B-DPO, I get errors such as: 

In the case of NousResearch/Nous-Hermes-2-Mixtral-8x7B-DPO:
` 
Traceback (most recent call last):
  File "/home/ubuntu/deepspeed_script.py", line 4, in <module>
    pipe = mii.pipeline("NousResearch/Nous-Hermes-2-Mixtral-8x7B-DPO")
  File "/home/ubuntu/.local/lib/python3.10/site-packages/mii/api.py", line 156, in pipeline
    inference_engine = load_model(model_config)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/mii/modeling/models.py", line 17, in load_model
    inference_engine = build_hf_engine(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/deepspeed/inference/v2/engine_factory.py", line 126, in build_hf_engine
    return InferenceEngineV2(policy, engine_config)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/deepspeed/inference/v2/engine_v2.py", line 83, in __init__
    self._model = self._policy.build_model(self._config, self._base_mp_group)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/deepspeed/inference/v2/model_implementations/inference_policy_base.py", line 156, in build_model
    self.model = self.instantiate_model(engine_config, mp_group)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/deepspeed/inference/v2/model_implementations/mixtral/policy.py", line 17, in instantiate_model
    return MixtralInferenceModel(config=self._model_config, engine_config=engine_config, base_mp_group=mp_group)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/deepspeed/inference/v2/model_implementations/mixtral/model.py", line 159, in __init__
    super().__init__(config, engine_config, base_mp_group)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/deepspeed/inference/v2/model_implementations/inference_transformer_base.py", line 222, in __init__
    self.make_unembedding_layer()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/deepspeed/inference/v2/model_implementations/inference_transformer_base.py", line 265, in make_unembedding_layer
    self.unembed = heuristics.instantiate_unembed(unembed_config, self._engine_config)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/deepspeed/inference/v2/modules/heuristics.py", line 179, in instantiate_unembed
    return DSUnembedRegistry.instantiate_config(config)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/deepspeed/inference/v2/modules/module_registry.py", line 39, in instantiate_config
    return cls.registry[config_bundle.name](config_bundle.config, config_bundle.implementation_config)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/deepspeed/inference/v2/modules/implementations/unembed/ragged_unembed.py", line 69, in __init__
    self._act_fn = CUDABiasActivation(self._config.vocab_size, self._config.dtype, ActivationType.IDENTITY)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/deepspeed/inference/v2/kernels/core_ops/bias_activations/bias_activation.py", line 36, in __init__
    raise ValueError("channels must be divisible by 8")
ValueError: channels must be divisible by 8 
` 

In the case of mistralai/Mixtral-8x7B-Instruct-v0.1: 
` 
Traceback (most recent call last):
  File "/home/ubuntu/deepspeed_script.py", line 11, in <module>
    output = pipe([full_prompt], max_new_tokens=512)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/mii/batching/ragged_batching.py", line 481, in __call__
    self.generate()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/mii/batching/utils.py", line 31, in wrapper
    return func(self, *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/mii/batching/ragged_batching.py", line 101, in generate
    next_token_logits = self.put(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/mii/batching/ragged_batching.py", line 448, in put
    return self.inference_engine.put(uids, tokenized_input, do_checks=False)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/deepspeed/inference/v2/engine_v2.py", line 146, in put
    logits = self._model.forward(self._batch)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/deepspeed/inference/v2/model_implementations/mixtral/model.py", line 259, in forward
    residual, hidden_states = self._forward_transformer(layer_idx, residual, hidden_states, wrapped_batch)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/deepspeed/inference/v2/model_implementations/mixtral/model.py", line 214, in _forward_transformer
    hidden_states = self.moe(hidden_states, ragged_batch_info, cur_params.moe_gate, cur_params.moe_mlp_1,
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/deepspeed/inference/v2/modules/implementations/moe/cutlass_multi_gemm.py", line 223, in forward
    self._mlp_1(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/deepspeed/inference/v2/kernels/cutlass_ops/moe_gemm/moe_gemm.py", line 59, in __call__
    self.kernel(ordered_output, ordered_input, weights, biases, total_rows_before_expert, self.act_fn)
RuntimeError: [FT Error][MoE][GEMM Dispatch] Arch unsupported for MoE GEMM
Traceback (most recent call last):
  File "/home/ubuntu/deepspeed_script.py", line 11, in <module>
    output = pipe([full_prompt], max_new_tokens=512)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/mii/batching/ragged_batching.py", line 494, in __call__
    self.generate()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/mii/batching/utils.py", line 31, in wrapper
    return func(self, *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/mii/batching/ragged_batching.py", line 101, in generate
    next_token_logits = self.put(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/mii/batching/ragged_batching.py", line 448, in put
    return self.inference_engine.put(uids, tokenized_input, do_checks=False)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/deepspeed/inference/v2/engine_v2.py", line 146, in put
    logits = self._model.forward(self._batch)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/deepspeed/inference/v2/model_implementations/mixtral/model.py", line 259, in forward
    residual, hidden_states = self._forward_transformer(layer_idx, residual, hidden_states, wrapped_batch)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/deepspeed/inference/v2/model_implementations/mixtral/model.py", line 214, in _forward_transformer
    hidden_states = self.moe(hidden_states, ragged_batch_info, cur_params.moe_gate, cur_params.moe_mlp_1,
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/deepspeed/inference/v2/modules/implementations/moe/cutlass_multi_gemm.py", line 223, in forward
    self._mlp_1(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/deepspeed/inference/v2/kernels/cutlass_ops/moe_gemm/moe_gemm.py", line 59, in __call__
    self.kernel(ordered_output, ordered_input, weights, biases, total_rows_before_expert, self.act_fn)
RuntimeError: [FT Error][MoE][GEMM Dispatch] Arch unsupported for MoE GEMM
`

The code used to load and infer model:
`
import mii
pipe = mii.pipeline("mistralai/Mixtral-8x7B-Instruct-v0.1")
system_prompt = "You are a sentient, superintelligent artificial general intelligence, here to teach and assist me."
full_prompt = f"<|im_start|>system\n{system_prompt}<|im_end|>\n<|im_start|>user\n what is AI?<|im_end|>\n<|im_start|>assistant"
output = pipe([full_prompt], max_new_tokens=512)
print("Generated Text:", output)
`

Also is it possible to benchmark the tokens/s ? 
Kind regards.

**Comment by arashb** [comment]
@S-Yacer for the issue with `NousResearch/Nous-Hermes-2-Mixtral-8x7B-DPO` model please see https://github.com/microsoft/DeepSpeed-MII/issues/385#issuecomment-1909194115

Regarding the `mistralai/Mixtral-8x7B-Instruct-v0.1` model, what is the GPU you are running on and what is your tensor parallel size? I just ran it on a 8xA100 node with 8-way TP and it worked fine!

**Comment by S-Yacer** [comment]
thanks for the very prompt response, I looked at the comment and look forward for the update ! 
in regards to the GPU I am using and tensor parallel size: I am using x2 H100 gpus.

**Comment by arashb** [comment]
@S-Yacer a few of our [kernels](https://github.com/microsoft/DeepSpeed-Kernels/blob/bdb30fdf51bab5053a6a4143823e8cb81d808c2e/dskernels/ft_gemm/gemm_variants/fpA_intB_gemm/fpA_intB_gemm_template.h#L433) are not enabled/tested on H100 yet, unfortunately! We will be adding full h100 support soon! thanks.

**Comment by S-Yacer** [comment]
thanks, looking forward ^^

**Comment by YJHMITWEB** [comment]
Hi @arashb , is there a way to use expert_parallelism in current Mii examples?
```
import mii
pipe = mii.pipeline("mistralai/Mixtral-8x7B-Instruct-v0.1")
response = pipe(["DeepSpeed is", "Seattle is"], max_new_tokens=128)
print(response)
```
`deepspeed --num_gpus 4 mii_example.py`, this I assume just doing tensor parallelism.

**Comment by arashb** [comment]
> Hi @arashb , is there a way to use expert_parallelism in current Mii examples?
@YJHMITWEB Sorry, we don't support EP with DeepSpeed-FastGen/MII, only TP is supported!

**Comment by iteratorlee** [comment]
> > Hi @arashb , is there a way to use expert_parallelism in current Mii examples?
> 
> @YJHMITWEB Sorry, we don't support EP with DeepSpeed-FastGen/MII, only TP is supported!

 Any plan to support EP in MoE inference? Or why is EP abandoned at the initial design? Thanks.

**Comment by YJHMITWEB** [comment]
@arashb Hi, thanks for the reply. Is MII built on top of DeepSpeed? Since I know that DeepSpeed does support Expert Parallelism.

**Comment by nikolakopoulos** [comment]
Any news on adding support for H100 GPUs?
