### ISSUE TITLE
RuntimeError: server crashed for some reason, unable to proceed

### ISSUE THREAD

**Issue by bao-xiaoyi** [microsoft/DeepSpeed-MII#400]
import mii
client  = mii.serve("/home/codellama/Mixtral-8x7B-Instruct-v0.1")
output = client.generate([question], max_new_tokens=256, do_sample=False)

get：
Traceback (most recent call last):
  File "/home/eval/evaluate_mixtral_json.py", line 254, in <module>
    main()
  File "/home/eval/evaluate_mixtral_json.py", line 242, in main
    score = eval_subject( test_df,
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/eval/evaluate_mixtral_json.py", line 171, in eval_subject
    client  = mii.serve("/home/kas/kas_workspace/sunyuzhao/codellama/Mixtral-8x7B-Instruct-v0.1")
  File "/usr/local/lib/python3.10/dist-packages/mii/api.py", line 124, in serve
    import_score_file(mii_config.deployment_name, DeploymentType.LOCAL).init()
  File "/tmp/mii_cache/Mixtral-8x7B-Instruct-v0.1-mii-deployment/score.py", line 33, in init
    mii.backend.MIIServer(mii_config)
  File "/usr/local/lib/python3.10/dist-packages/mii/backend/server.py", line 47, in __init__
    self._wait_until_server_is_live(processes,
  File "/usr/local/lib/python3.10/dist-packages/mii/backend/server.py", line 62, in _wait_until_server_is_live
    raise RuntimeError(
RuntimeError: server crashed for some reason, unable to proceed

**Comment by mrwyattii** [comment]
Hi @bao-xiaoyi I notice that you are not setting a `tensor_parallel` value in this line `client = mii.serve("/home/codellama/Mixtral-8x7B-Instruct-v0.1")`

I server will default to using a single GPU and I suspect that is causing an out of memory error. What GPU are you running on? You will need 2 or more A100-80GB to run the Mixtral model.

**Comment by bao-xiaoyi** [comment]
> 你好@bao-xiaoyi我注意到您没有`tensor_parallel`在此行中设置值`client = mii.serve("/home/codellama/Mixtral-8x7B-Instruct-v0.1")`
> 
> 我的服务器默认使用单个 GPU，我怀疑这会导致内存不足错误。您运行在什么 GPU 上？您将需要 2 个或更多 A100-80GB 才能运行 Mixtral 模型。

The problem has been resolved, thank you
