### ISSUE TITLE
When I start server, after loading model, I got an error of 'grpc.aio._call.AioRpcError'

### ISSUE THREAD

**Issue by zzz0906** [microsoft/DeepSpeed-MII#424]
# Error Name

grpc.aio._call.AioRpcError

# Scripts:

MODELS=(NousResearch/Llama-2-13b-hf)

https://github.com/microsoft/DeepSpeedExamples/blob/master/benchmarks/inference/mii/run_all.sh

# Error Details
```
[2024-02-28 04:13:29,294] [INFO] [engine_v2.py:84:__init__] Model built.
[2024-02-28 04:13:29,312] [INFO] [kv_cache.py:135:__init__] Allocating KV-cache 0 with shape: (40, 561, 64, 2, 40, 128) consisting of 561 blocks.
Starting server on port: 50051
About to start server
Started
[2024-02-28 04:13:32,307] [INFO] [server.py:65:_wait_until_server_is_live] waiting for server to start...
[2024-02-28 04:13:32,307] [INFO] [server.py:65:_wait_until_server_is_live] waiting for server to start...
[2024-02-28 04:13:37,312] [INFO] [server.py:65:_wait_until_server_is_live] waiting for server to start...
[2024-02-28 04:13:37,312] [INFO] [server.py:65:_wait_until_server_is_live] waiting for server to start...
[2024-02-28 04:13:37,312] [INFO] [server.py:70:_wait_until_server_is_live] server has started on ports [50051]
[2024-02-28 04:13:37,312] [INFO] [server.py:70:_wait_until_server_is_live] server has started on ports [50051]
warmup queue size: 513 (48622)
Process Process-1:
Traceback (most recent call last):
  File "/soft/datascience/conda/2022-09-08/mconda3/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/soft/datascience/conda/2022-09-08/mconda3/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/xxx/xxx/DeepSpeedExamples/benchmarks/inference/mii/src/client.py", line 148, in _run_parallel
    call_mii(client, input_tokens, req_max_new_tokens, stream)
  File "/xxx/xxx/DeepSpeedExamples/benchmarks/inference/mii/src/client.py", line 43, in call_mii
    client.generate(
  File "/xxx/xxx/DeepSpeed-MII-internal/mii/backend/client.py", line 72, in generate
    return self._generate_stream(streaming_fn, prompts, **query_kwargs)
  File "/xxx/xxx/DeepSpeed-MII-internal/mii/backend/client.py", line 95, in _generate_stream
    self.asyncio_loop.run_until_complete(put_result())
  File "/soft/datascience/conda/2022-09-08/mconda3/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/xxx/xxx/DeepSpeed-MII-internal/mii/backend/client.py", line 90, in put_result
    response = await response_stream.__anext__()
  File "/xxx/xxx/DeepSpeed-MII-internal/mii/backend/client.py", line 54, in _request_async_response_stream
    async for response in getattr(self.stub,
  File "/grand/datascience/lib/python3.8/site-packages/grpc/aio/_call.py", line 356, in _fetch_stream_responses
    await self._raise_for_status()
  File "/grand/datascience/lib/python3.8/site-packages/grpc/aio/_call.py", line 263, in _raise_for_status
    raise _create_rpc_error(
grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:140.221.69.42:3128: HTTP proxy returned response code 403"
        debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2024-02-28T04:13:38.810645961+00:00", grpc_status:14, grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:140.221.69.42:3128: HTTP proxy returned response code 403"}"
```

**Comment by xiaoxiawu-microsoft** [comment]
@mrwyattii could you help looking into this? Many thanks!

**Comment by mrwyattii** [comment]
Hi @zzz0906 I'm unable to reproduce this error on my side. I'm using DeepSpeed@0.13.4 and DeepSpeed-MII@0.2.2

Could you help me by running the following python script? This will help me understand whether it's a problem with DeepSpeed-MII or with the benchmark code.
```python
import mii

client = mii.serve("NousResearch/Llama-2-13b-hf")
r = client("test input", max_new_tokens=128)
print(r)
```

**Comment by zzz0906** [comment]
> Hi @zzz0906 I'm unable to reproduce this error on my side. I'm using DeepSpeed@0.13.4 and DeepSpeed-MII@0.2.2
> 
> Could you help me by running the following python script? This will help me understand whether it's a problem with DeepSpeed-MII or with the benchmark code.
> 
> ```python
> import mii
> 
> client = mii.serve("NousResearch/Llama-2-13b-hf")
> r = client("test input", max_new_tokens=128)
> print(r)
> ```

Sure when I run the second line > r = client("test input", max_new_tokens=128) I got an error of:
```
>>> r = client("test input", max_new_tokens=128)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/lus/xxxx/projects/xxx/xxx/DeepSpeed-MII-internal/mii/backend/client.py", line 42, in __call__
    return self.generate(*args, **kwargs)
  File "/lus/xxxx/projects/xxx/xxx/DeepSpeed-MII-internal/mii/backend/client.py", line 74, in generate
    return self.asyncio_loop.run_until_complete(
  File "/soft/conda/2022-09-08/mconda3/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/lus/xxxx/projects/xxx/xxx/DeepSpeed-MII-internal/mii/backend/client.py", line 47, in _request_async_response
    proto_response = await getattr(self.stub, task_methods.method)(proto_request)
  File "/xxxx/xxx/xxx/xxx/xxx/lib/python3.8/site-packages/grpc/aio/_call.py", line 318, in __await__
    raise _create_rpc_error(
grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:140.221.69.42:3128: HTTP proxy returned response code 403"
        debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2024-02-28T20:12:18.414690102+00:00", grpc_status:14, grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:140.221.69.42:3128: HTTP proxy returned response code 403"}"
```

**Comment by mrwyattii** [comment]
Thanks @zzz0906. Because you're not able to able to run even a simple example, can you share some information about your python environment? Please run the following and share the output: `pip list | grep "asyncio\|grpc\|deepspeed\|torch"`

Can you also ensure that no orphaned MII processes are running in the background with `ps aux | grep "mii"`. When you run this, it should only show a single line like this:
```
michael+ 2763709  0.0  0.0   6440  2588 pts/3    S+   15:49   0:00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn --exclude-dir=.idea --exclude-dir=.tox mii
```

**Comment by zzz0906** [comment]
> Thanks @zzz0906. Because you're not able to able to run even a simple example, can you share some information about your python environment? Please run the following and share the output: `pip list | grep "asyncio\|grpc\|deepspeed\|torch"`
> 
> Can you also ensure that no orphaned MII processes are running in the background with `ps aux | grep "mii"`. When you run this, it should only show a single line like this:
> 
> ```
> michael+ 2763709  0.0  0.0   6440  2588 pts/3    S+   15:49   0:00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn --exclude-dir=.idea --exclude-dir=.tox mii
> ```

Sure,
1. pip list | grep "asyncio\|grpc\|deepspeed\|torch"
```
asyncio                           3.4.3
deepspeed                         0.13.2+83eb2201       /lus/grand/projects/DeepSpeed-internal
deepspeed-kernels                 0.0.1.dev1698255861
deepspeed-mii                     0.2.1+4cc5d90         /lus/grand/projects/DeepSpeed-MII-internal
functorch                         0.3.0a0+091d999
gpytorch                          1.9.0
grpcio                            1.62.0
grpcio-tools                      1.62.0
nest-asyncio                      1.5.5
pytorch-lightning                 1.7.5
qtorch                            0.3.0
torch                             1.12.0a0+git664058f
torch-geometric                   2.1.0.post1
torch-scatter                     2.0.9
torch-sparse                      0.6.15
torch-tb-profiler                 0.4.0
torchinfo                         1.7.0
torchmetrics                      0.9.3
torchvision                       0.13.0a0+da3794e
torchviz                          0.0.2
```
2.  Yeah, when I run it I found there are orphaned MII processes are running. I killed them and rerun this
ps aux | grep "mii"
```
mic+ 19204  0.0  0.0   8216   804 pts/0    S+   01:41   0:00 grep --color=auto mii
```
```
import mii
client = mii.serve("NousResearch/Llama-2-13b-hf")
r = client("test input", max_new_tokens=128)
print(r)
```
got the following output now:
```
>>> r = client("test input", max_new_tokens=128)
>>> print(r)
[and output files at the shell prompt.
"ERROR",  // system error occurred.
"FATAL",  // critical system error occurred.
code, and fileName + errDesc as the output.
file without modification. If successful, the process should write the updated output file.
file without modification. If successful, the process should write the updated output file to outputFileName.
// From now on, I am getting the input file and output file names in runtime as below.]
```
