### ISSUE TITLE
mii example FileNotFoundError: [Errno 2] No such file or directory: '/tmp/mii_cache/bert-base-uncased_deployment/score.py'

### ISSUE THREAD

**Issue by koliaok** [microsoft/DeepSpeed-MII#51]
Python=3.8
Deepspeed-MII=latest version

test example in mii.py file
```
import mii

# roberta
name = "roberta-base"
mask = "<mask>"
# bert
name = "bert-base-uncased"
mask = "[MASK]"
print(f"Querying {name}...")

generator = mii.mii_query_handle(name + "_deployment")
result = generator.query({'query': "Hello I'm a " + mask + " model."})
print(result.response)
print("time_taken:", result.time_taken)
```

python mii.py 

Error code

```
(ds1) [root@6301babb8dc8a1eeb0ed2044 DeepSpeed-MII (main)]# python mii.py
Querying bert-base-uncased...
Traceback (most recent call last):
  File "mii.py", line 11, in <module>
    generator = mii.mii_query_handle(name + "_deployment")
  File "/root/workspace/sharing/big-storage/hyungrak/tuning/text_filter/mii_test/DeepSpeed-MII/mii/server_client.py", line 34, in mii_query_handle
    configs = mii.utils.import_score_file(deployment_name).configs
  File "/root/workspace/sharing/big-storage/hyungrak/tuning/text_filter/mii_test/DeepSpeed-MII/mii/utils.py", line 147, in import_score_file
    spec.loader.exec_module(score)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 975, in get_code
  File "<frozen importlib._bootstrap_external>", line 1032, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/mii_cache/bert-base-uncased_deployment/score.py'
```

why are this error occuring

**Comment by koliaok** [comment]
My miss, not mii.deploy code befor mii_query_handle, sorry about that~ thank u
