### ISSUE TITLE
Non-persistent example fails with KeyError

### ISSUE THREAD

**Issue by jjaymick001** [microsoft/DeepSpeed-MII#536]
The following example is provided as a non-persistent example.
`import mii
pipe = mii.pipeline("mistralai/Mistral-7B-v0.1")
response = pipe(["DeepSpeed is", "Seattle is"], max_new_tokens=128)
print(response)`

Running this code via deepspeed as:
deepspeed --num_gpus 1 mii-test.py

Fails with the following output.

[rank0]: Traceback (most recent call last):
[rank0]:   File "/root/DeepSpeed/examples/inference/huggingface/zero_inference/mii-test.py", line 2, in <module>
[rank0]:     pipe = mii.pipeline("mistralai/Mistral-7B-v0.1")
[rank0]:   File "/root/deepspeed/lib/python3.10/site-packages/mii/api.py", line 231, in pipeline
[rank0]:     inference_engine = load_model(model_config)
[rank0]:   File "/root/deepspeed/lib/python3.10/site-packages/mii/modeling/models.py", line 17, in load_model
[rank0]:     inference_engine = build_hf_engine(
[rank0]:   File "/root/deepspeed/lib/python3.10/site-packages/deepspeed/inference/v2/engine_factory.py", line 93, in build_hf_engine
[rank0]:     checkpoint_engine = HuggingFaceCheckpointEngine(path)
[rank0]:   File "/root/deepspeed/lib/python3.10/site-packages/deepspeed/inference/v2/checkpoint/huggingface_engine.py", line 24, in __init__
[rank0]:     self.model_config = AutoConfig.from_pretrained(self.model_name_or_path, **hf_kwargs)
[rank0]:   File "/root/deepspeed/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 1028, in from_pretrained
[rank0]:     config_class = CONFIG_MAPPING[config_dict["model_type"]]
[rank0]:   File "/root/deepspeed/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 726, in __getitem__
[rank0]:     raise KeyError(key)
[rank0]: KeyError: 'mistral'

dsreport off my system

2024-10-29 21:50:27,584] [INFO] [real_accelerator.py:219:get_accelerator] Setting ds_accelerator to cuda (auto detect)
/root/deepspeed/lib/python3.10/site-packages/transformers/utils/generic.py:260: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  torch.utils._pytree._register_pytree_node(
/root/deepspeed/lib/python3.10/site-packages/transformers/utils/generic.py:260: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  torch.utils._pytree._register_pytree_node(
--------------------------------------------------
DeepSpeed C++/CUDA extension op report
--------------------------------------------------
NOTE: Ops not installed will be just-in-time (JIT) compiled at
      runtime if needed. Op compatibility means that your system
      meet the required dependencies to JIT install the op.
--------------------------------------------------
JIT compiled ops requires ninja
ninja .................. [OKAY]
--------------------------------------------------
op name ................ installed .. compatible
--------------------------------------------------
async_io ............... [NO] ....... [OKAY]
fused_adam ............. [NO] ....... [OKAY]
cpu_adam ............... [NO] ....... [OKAY]
cpu_adagrad ............ [NO] ....... [OKAY]
cpu_lion ............... [NO] ....... [OKAY]
 [WARNING]  Please specify the CUTLASS repo directory as environment variable $CUTLASS_PATH
evoformer_attn ......... [NO] ....... [NO]
 [WARNING]  FP Quantizer is using an untested triton version (3.1.0), only 2.3.(0, 1) and 3.0.0 are known to be compatible with these kernels
fp_quantizer ........... [NO] ....... [NO]
fused_lamb ............. [NO] ....... [OKAY]
fused_lion ............. [NO] ....... [OKAY]
x86_64-linux-gnu-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -c /tmp/tmpn_ff2b7b/test.c -o /tmp/tmpn_ff2b7b/test.o
x86_64-linux-gnu-gcc /tmp/tmpn_ff2b7b/test.o -L/usr/local/cuda -L/usr/local/cuda/lib64 -lcufile -o /tmp/tmpn_ff2b7b/a.out
x86_64-linux-gnu-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -c /tmp/tmp1vi0yr9a/test.c -o /tmp/tmp1vi0yr9a/test.o
x86_64-linux-gnu-gcc /tmp/tmp1vi0yr9a/test.o -laio -o /tmp/tmp1vi0yr9a/a.out
gds .................... [NO] ....... [OKAY]
transformer_inference .. [NO] ....... [OKAY]
inference_core_ops ..... [NO] ....... [OKAY]
cutlass_ops ............ [NO] ....... [OKAY]
quantizer .............. [NO] ....... [OKAY]
ragged_device_ops ...... [NO] ....... [OKAY]
ragged_ops ............. [NO] ....... [OKAY]
random_ltd ............. [NO] ....... [OKAY]
 [WARNING]  sparse_attn requires a torch version >= 1.5 and < 2.0 but detected 2.5
 [WARNING]  using untested triton version (3.1.0), only 1.0.0 is known to be compatible
sparse_attn ............ [NO] ....... [NO]
spatial_inference ...... [NO] ....... [OKAY]
transformer ............ [NO] ....... [OKAY]
stochastic_transformer . [NO] ....... [OKAY]
--------------------------------------------------
DeepSpeed general environment info:
torch install path ............... ['/root/deepspeed/lib/python3.10/site-packages/torch']
torch version .................... 2.5.0+cu124
deepspeed install path ........... ['/root/deepspeed/lib/python3.10/site-packages/deepspeed']
deepspeed info ................... 0.15.3, unknown, unknown
torch cuda version ............... 12.4
torch hip version ................ None
nvcc version ..................... 12.4
deepspeed wheel compiled w. ...... torch 2.5, cuda 12.4
shared memory (/dev/shm) size .... 125.66 GB

**Comment by jjaymick001** [comment]
I ended up creating a new venv and it appears to be working.
I was leveraging a venv that had deepspeed requirements installed then I added deepspeed-mii requirements.
I think there is some conflict between the requirements for deepspeed and deepspeed-mii
Unclear. but this can be considered closed.
