### ISSUE TITLE
Error in inf/nan tensors

### ISSUE THREAD

**Issue by mayank31398** [microsoft/DeepSpeed-MII#84]
@mrwyattii 
```shell
Traceback (most recent call last):
  File "/net/llm-shared-nfs/nfs/yelkurdi/conda/miniconda3/envs/bloom-server/lib/python3.8/site-packages/mii/server_client.py", line 268, in _request_async_response
    response = await self.stubs[stub_id].GeneratorReply(req)
  File "/net/llm-shared-nfs/nfs/yelkurdi/conda/miniconda3/envs/bloom-server/lib/python3.8/site-packages/grpc/aio/_call.py", line 285, in __await__
    raise _create_rpc_error(self._cython_call._initial_metadata,
grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
        status = StatusCode.UNKNOWN
        details = "Exception calling application: probability tensor contains either `inf`, `nan` or element < 0"
        debug_error_string = "{"created":"@1667201081.916813042","description":"Error received from peer ipv6:[::1]:50956","file":"src/core/lib/surface/call.cc","file_line":1068,"grpc_message":"Exception calling application: probability tensor contains either `inf`, `nan` or element < 0","grpc_status":2}"
```
I see this sometimes for BLOOM-176B

**Comment by mrwyattii** [comment]
Is this happening when you are deploying the model or running a query? Could you share anything that might help me reproduce this error?

**Comment by mayank31398** [comment]
I will try to reproduce this. But I think this is happening in the DS-inference code and is not specific to MII.
It happens while running a query.

**Comment by mrwyattii** [comment]
closing due to inactivity, please reopen if you are able to reproduce
